/**
 * Shared constants for the feature-docs generator.
 *
 * Owns the source tree roots, the per-folder file shape, and the placeholder
 * tokens emitted into `DOCS.md` when a hand-written source is missing or
 * incomplete. The hard gate (`pnpm features:check:strict`) ratchets against
 * the locked baseline at {@link MISSING_TOKENS_BASELINE_FILE}: counts may
 * decrease (and the baseline can be refreshed via
 * `pnpm features:refresh-baseline`); they may not increase.
 */
import { resolve } from 'node:path';

export const REPO_ROOT = resolve(process.cwd());
export const SRC_ROOT = resolve(REPO_ROOT, 'src');
export const DOMAINS_ROOT = resolve(SRC_ROOT, 'domains');
export const INFRASTRUCTURE_ROOT = resolve(SRC_ROOT, 'infrastructure');
export const SHARED_ROOT = resolve(SRC_ROOT, 'shared');
export const SCRIPTS_ROOT = resolve(SRC_ROOT, 'scripts');
export const CORE_ROOT = resolve(SRC_ROOT, 'core');
export const TESTS_ROOT = resolve(SRC_ROOT, 'tests');

export const PER_FOLDER_DOCS_FILENAME = 'DOCS.md';
export const PER_FOLDER_OVERVIEW_FILENAME = 'OVERVIEW.md';
export const SRC_DOCS_INDEX_FILENAME = 'DOCS.md';
export const SRC_OVERVIEW_FILENAME = 'OVERVIEW.md';
export const SRC_PATTERNS_FILENAME = 'PATTERNS.md';
export const SRC_FLOWS_FILENAME = 'FLOWS.md';
export const SRC_POLICIES_FILENAME = 'POLICIES.md';

export const FOLDER_NAMES_TO_SKIP = new Set([
  'node_modules',
  'dist',
  '.git',
  '__tests__',
  '__test__',
  '__mocks__',
  '__fixtures__',
  'fixtures',
  'helpers',
  'factories',
]);

export const ALLOWED_TYPESCRIPT_EXTENSIONS = ['.ts'];

export const TEST_FILE_SUFFIXES = [
  '.test.ts',
  '.spec.ts',
  '.unit.test.ts',
  '.integration.test.ts',
  '.e2e.test.ts',
  '.contract.test.ts',
  '.chaos.test.ts',
  '.property.test.ts',
  '.security.test.ts',
  '.performance.test.ts',
  '.global.test.ts',
];

export const SERVICE_LIKE_FILE_PATTERN = /\.(service|worker|processor)\.ts$/;
export const POLICY_LIKE_FILE_PATTERN = /\.policy\.ts$/;

export const DOCS_GENERATED_BANNER =
  '> Auto-generated by `pnpm features:generate`. Do not edit by hand.';

export const MISSING_DESCRIPTION_TOKEN = '<!-- MISSING_DESCRIPTION -->';
export const MISSING_REMARKS_TOKEN = '<!-- MISSING_REMARKS -->';
export const MISSING_OVERVIEW_SECTION_TOKEN = '<!-- MISSING_OVERVIEW_SECTION -->';
export const MISSING_SYSTEM_FILE_TOKEN = '<!-- MISSING_SYSTEM_FILE -->';

export const MISSING_TOKENS = [
  MISSING_DESCRIPTION_TOKEN,
  MISSING_REMARKS_TOKEN,
  MISSING_OVERVIEW_SECTION_TOKEN,
  MISSING_SYSTEM_FILE_TOKEN,
];

export const MISSING_TOKENS_BASELINE_FILE = resolve(
  REPO_ROOT,
  'tooling/feature-docs/missing-tokens.baseline.json',
);
