/** Generated src/ structure tree output path and walk options. */
export const SRC_STRUCTURE_TREE_OUTPUT_PATH = 'docs/reference/architecture/src-structure-tree.txt';

/** Root directory scanned when building the committed structure tree. */
export const SRC_ROOT = 'src';

/** Directory names omitted when writing the committed structure tree file. */
export const SKIP_DIRS_WRITE = new Set(['node_modules', '.vite', 'dist', 'coverage']);

/** Directory names omitted when printing the legacy stdout tree (includes `__tests__`). */
export const SKIP_DIRS_STDOUT = new Set([...SKIP_DIRS_WRITE, '__tests__']);

/** File names skipped during tree walks (placeholder files). */
export const SKIP_FILE_NAMES = new Set(['.gitkeep']);

/** Header comment prepended to the committed structure tree artifact. */
export const STRUCTURE_TREE_HEADER = `# Generated by pnpm tool:project-structure-tree — do not edit
# Regenerate: pnpm tool:project-structure-tree
# Layout rules: CLAUDE.md, docs/reference/architecture/project-structure-guide.md
# Routes: pnpm routes:catalog → docs/routes.txt
`;
