/**
 * Generates project identity artifacts from tooling/setup/setup.config.json.
 *
 * Usage:
 *   pnpm tool:generate-project-identity
 *   pnpm tool:generate-project-identity:check
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadConfig } from '@tooling/setup/common/config.js';
import { buildProjectIdentitySnapshot } from './project-identity.util.js';
import { validateWorkflowLiteralsAgainstManifest } from './validate-project-identity-workflows.js';

const REPOSITORY_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

const GENERATED_BANNER =
  '// GENERATED by pnpm tool:generate-project-identity — do not edit; change tooling/setup/setup.config.json instead.\n';

const OUTPUT_PATHS = {
  constants: resolve(REPOSITORY_ROOT, 'src/shared/constants/project-identity.constants.ts'),
  compositeAction: resolve(REPOSITORY_ROOT, '.github/actions/setup-project-identity/action.yml'),
  projectIdentityEnv: resolve(REPOSITORY_ROOT, '.github/project-identity.env'),
  branchMapShell: resolve(REPOSITORY_ROOT, '.github/generated/branch-environment-map.sh'),
  dockerBake: resolve(REPOSITORY_ROOT, 'docker-bake.hcl'),
  openApiLocaleEn: resolve(REPOSITORY_ROOT, 'src/shared/locales/en/openapi.json'),
  openApiLocaleEs: resolve(REPOSITORY_ROOT, 'src/shared/locales/es/openapi.json'),
} as const;

const WORKFLOW_FILES_TO_PATCH = [
  'pr-ci.yml',
  'post-merge-ci.yml',
  'pr-docs-lane.yml',
  'reusable-docker-build-trivy.yml',
  'reusable-railway-deploy.yml',
  'scheduled-monthly-restore-rto.yml',
  'scheduled-weekly-restore-smoke.yml',
  'scheduled-chaos.yml',
  'cleanup-cache.yml',
  'cleanup-ghcr.yml',
  'bootstrap-railway-service.yml',
  'post-release-backmerge.yml',
  'reusable-vitest-postgres-redis.yml',
] as const;

const LEGACY_DEPLOY_CASE_BLOCK = `              main) echo "environment=production"  >> "$GITHUB_OUTPUT" ;;
              dev)  echo "environment=development" >> "$GITHUB_OUTPUT" ;;`;

const LEGACY_SCHEDULED_CHAOS_BRANCH_GUARD = `          if [ "$branch" != "main" ] && [ "$branch" != "dev" ]; then
            branch="dev"
          fi`;

const LEGACY_CLEANUP_CACHE_BRANCH_GUARD =
  '                if [ "$WF_RUN_BRANCH" = "dev" ] || [ "$WF_RUN_BRANCH" = "main" ]; then\n' +
  '                  mode="lru"\n' +
  '                  if [ "$WF_RUN_CONCLUSION" = "failure" ]; then\n' +
  '                    keep_count="${KEEP_FAILED_RUNS}"\n' +
  '                  fi\n' +
  '                fi';

function renderConstants(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const { slug, displayName, artifacts, git, branchEnvironmentMap } = snapshot;
  const escapedDisplay = displayName.replace(/'/g, "\\'");
  return `${GENERATED_BANNER}
/** Canonical project slug (Neon, Sentry, JWT issuer, MCP URI scheme). */
export const PROJECT_SLUG = '${slug}';

/** Human-facing product name for OpenAPI and emails. */
export const PROJECT_DISPLAY_NAME = '${escapedDisplay}';

/** Default OpenAPI \`info.title\` when locale strings omit a title. */
export const PROJECT_OPENAPI_TITLE = '${escapedDisplay} API';

/** JWT \`iss\` claim — changing this invalidates outstanding tokens. */
export const JWT_ISSUER = PROJECT_SLUG;

/** TOTP issuer shown in authenticator apps. */
export const TOTP_ISSUER = PROJECT_SLUG;

/** WebAuthn RP display name when \`WEBAUTHN_RP_NAME\` is unset. */
export const WEBAUTHN_RP_NAME_DEFAULT = PROJECT_SLUG;

/** MCP resource URI scheme prefix (\`{slug}://\`). */
export const MCP_URI_SCHEME = '${slug}';

/** MCP resource URI for the bundled OpenAPI document. */
export const MCP_OPENAPI_RESOURCE_URI = '${slug}://openapi';

/** MCP resource URI for the route catalog. */
export const MCP_ROUTES_RESOURCE_URI = '${slug}://routes';

/** OpenTelemetry service name for the API process. */
export const OTEL_SERVICE_NAME_API = '${artifacts.apiImage}';

/** OpenTelemetry service name for the worker process. */
export const OTEL_SERVICE_NAME_WORKER = '${artifacts.workerImage}';

/** OpenTelemetry tracer instrumentation scope name. */
export const OTEL_TRACER_NAME = PROJECT_SLUG;

/** Local Docker image tag for API smoke and PR verify builds. */
export const DOCKER_LOCAL_API_TAG = '${artifacts.dockerLocalApiTag}';

/** Local Docker image tag for worker images in compose and CI. */
export const DOCKER_LOCAL_WORKER_TAG = '${artifacts.workerImage}';

/** GHCR image repository name for the API container. */
export const GHCR_API_IMAGE_NAME = '${artifacts.apiImage}';

/** GHCR image repository name for the worker container. */
export const GHCR_WORKER_IMAGE_NAME = '${artifacts.workerImage}';

/** GHCR Actions cache scope key for API image layers. */
export const GHCR_CACHE_SCOPE_API = '${artifacts.ghcrCacheScopeApi}';

/** GHCR Actions cache scope key for worker image layers. */
export const GHCR_CACHE_SCOPE_WORKER = '${artifacts.ghcrCacheScopeWorker}';

/** Git branches that receive protected CI + deploy pipelines. */
export const PROTECTED_GIT_BRANCHES = [${[...git.protectedBranches].map((branch) => `'${branch}'`).join(', ')}] as const;

/** Default git branch for new clones and PR bases (typically \`dev\`). */
export const GIT_DEFAULT_BRANCH = '${git.defaultBranch}';

/** Production deploy branch (maps to production GitHub Environment). */
export const GIT_PRODUCTION_BRANCH = '${git.productionBranch}';

/** Non-production deploy branch (maps to development GitHub Environment). */
export const GIT_NON_PRODUCTION_BRANCH = '${git.nonProductionBranch}';

/** Maps git branch ref → hosted environment name (GitHub Environment / NODE_ENV). */
export const BRANCH_TO_ENVIRONMENT_MAP: Readonly<Record<string, string>> = {
${Object.entries(branchEnvironmentMap)
  .map(([branch, environment]) => `  ${branch}: '${environment}',`)
  .join('\n')}
};
`;
}

function renderCompositeAction(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const { slug, displayName, artifacts, git, branchEnvironmentMap } = snapshot;
  const protectedBranchesJson = JSON.stringify([...git.protectedBranches]);
  const branchEnvMapJson = JSON.stringify(branchEnvironmentMap);
  const echoLines = [
    `        echo "PROJECT_SLUG=${slug}" >> "$GITHUB_ENV"`,
    `        echo "PROJECT_DISPLAY_NAME=${displayName}" >> "$GITHUB_ENV"`,
    `        echo "API_IMAGE=${artifacts.apiImage}" >> "$GITHUB_ENV"`,
    `        echo "WORKER_IMAGE=${artifacts.workerImage}" >> "$GITHUB_ENV"`,
    `        echo "DOCKER_LOCAL_API_TAG=${artifacts.dockerLocalApiTag}" >> "$GITHUB_ENV"`,
    `        echo "GHCR_CACHE_SCOPE_API=${artifacts.ghcrCacheScopeApi}" >> "$GITHUB_ENV"`,
    `        echo "GHCR_CACHE_SCOPE_WORKER=${artifacts.ghcrCacheScopeWorker}" >> "$GITHUB_ENV"`,
    `        echo "GIT_DEFAULT_BRANCH=${git.defaultBranch}" >> "$GITHUB_ENV"`,
    `        echo "GIT_PRODUCTION_BRANCH=${git.productionBranch}" >> "$GITHUB_ENV"`,
    `        echo "GIT_NON_PRODUCTION_BRANCH=${git.nonProductionBranch}" >> "$GITHUB_ENV"`,
    `        echo 'PROTECTED_BRANCHES_JSON=${protectedBranchesJson}' >> "$GITHUB_ENV"`,
    `        echo 'BRANCH_ENV_MAP_JSON=${branchEnvMapJson}' >> "$GITHUB_ENV"`,
  ].join('\n');
  return `# GENERATED by pnpm tool:generate-project-identity — do not edit; change tooling/setup/setup.config.json instead.
name: Setup Project Identity
description: Sets project identity environment variables for the current job.
runs:
  using: composite
  steps:
    - name: Set project identity env vars
      shell: bash
      run: |
${echoLines}
`;
}

function renderProjectIdentityEnv(
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const lines = [
    '# GENERATED by pnpm tool:generate-project-identity — do not edit.',
    '# CI workflows use the generated composite action .github/actions/setup-project-identity/action.yml.',
    '# This file is for local scripts, docs, and tooling reference — not loaded by GitHub Actions.',
    `PROJECT_SLUG=${snapshot.slug}`,
    `PROJECT_DISPLAY_NAME=${snapshot.displayName}`,
    `API_IMAGE=${snapshot.artifacts.apiImage}`,
    `WORKER_IMAGE=${snapshot.artifacts.workerImage}`,
    `DOCKER_LOCAL_API_TAG=${snapshot.artifacts.dockerLocalApiTag}`,
    `GHCR_CACHE_SCOPE_API=${snapshot.artifacts.ghcrCacheScopeApi}`,
    `GHCR_CACHE_SCOPE_WORKER=${snapshot.artifacts.ghcrCacheScopeWorker}`,
    `GIT_DEFAULT_BRANCH=${snapshot.git.defaultBranch}`,
    `GIT_PRODUCTION_BRANCH=${snapshot.git.productionBranch}`,
    `GIT_NON_PRODUCTION_BRANCH=${snapshot.git.nonProductionBranch}`,
    `PROTECTED_BRANCHES_JSON=${JSON.stringify([...snapshot.git.protectedBranches])}`,
    `BRANCH_ENV_MAP_JSON=${JSON.stringify(snapshot.branchEnvironmentMap)}`,
    '',
  ];
  return lines.join('\n');
}

function renderBranchMapShell(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const cases = Object.entries(snapshot.branchEnvironmentMap)
    .map(([branch, environment]) => `    ${branch}) echo "${environment}" ;;`)
    .join('\n');
  return `#!/usr/bin/env bash
# GENERATED by pnpm tool:generate-project-identity — do not edit.
set -euo pipefail

map_branch_to_environment() {
  local branch="\${1:?branch required}"
  case "$branch" in
${cases}
    *)
      echo "::error::Unsupported branch for environment mapping: $branch" >&2
      return 1
      ;;
  esac
}
`;
}

function renderOpenApiLocale(localePath: string, openApiTitle: string): string | undefined {
  if (!existsSync(localePath)) {
    return undefined;
  }
  const parsed = JSON.parse(readFileSync(localePath, 'utf-8')) as {
    info?: { title?: string; description?: string };
    [key: string]: unknown;
  };
  if (!parsed.info) {
    return undefined;
  }
  parsed.info.title = openApiTitle;
  return `${JSON.stringify(parsed, null, 2)}\n`;
}

function renderDockerBake(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const apiTag = snapshot.artifacts.dockerLocalApiTag;
  const workerTag = snapshot.artifacts.workerImage;
  return `group "default" {
  targets = ["api", "worker"]
}

target "_common" {
  context    = "."
  dockerfile = "Dockerfile"
  args = {
    NODE_VERSION = "24.13.0"
    PNPM_VERSION = "11.1.1"
  }
}

target "api" {
  inherits = ["_common"]
  target   = "api"
  args = {
    GENERATE_MCP_DOCS = "true"
  }
  tags = ["${apiTag}:latest"]
}

target "worker" {
  inherits = ["_common"]
  target   = "worker"
  args = {
    GENERATE_MCP_DOCS = "false"
  }
  tags = ["${workerTag}:latest"]
}
`;
}

function patchWorkflowBranches(
  workflowContents: string,
  protectedBranches: readonly string[],
): string {
  const branchListYaml = protectedBranches.join(', ');
  let updated = workflowContents.replace(
    /branches:\s*\[[^\]]+\]/g,
    `branches: [${branchListYaml}]`,
  );
  updated = updated.replace(/fromJSON\('\[[^\]]+\]'\)/g, 'fromJSON(env.PROTECTED_BRANCHES_JSON)');
  return updated;
}

function patchPostMergeExpressions(
  workflowContents: string,
  productionBranch: string,
  nonProductionBranch: string,
  productionEnvironment: string,
  nonProductionEnvironment: string,
): string {
  return workflowContents
    .replace(
      /github\.ref_name == 'main' && 'production' \|\| 'development'/g,
      `github.ref_name == '${productionBranch}' && '${productionEnvironment}' || '${nonProductionEnvironment}'`,
    )
    .replace(
      /github\.ref_name == 'dev' && '\.dev' \|\| ''/g,
      `github.ref_name == '${nonProductionBranch}' && '.dev' || ''`,
    );
}

function patchDeployCaseBlocks(
  workflowContents: string,
  branchEnvironmentMap: Record<string, string>,
): string {
  if (!workflowContents.includes(LEGACY_DEPLOY_CASE_BLOCK)) {
    return workflowContents;
  }
  const caseBody = Object.entries(branchEnvironmentMap)
    .map(
      ([branch, environment]) =>
        `              ${branch}) echo "environment=${environment}"  >> "$GITHUB_OUTPUT" ;;`,
    )
    .join('\n');
  return workflowContents.split(LEGACY_DEPLOY_CASE_BLOCK).join(caseBody);
}

function patchScheduledChaosBranchGuard(
  workflowContents: string,
  branchGuard: string,
  nonProductionBranch: string,
): string {
  if (!workflowContents.includes(LEGACY_SCHEDULED_CHAOS_BRANCH_GUARD)) {
    return workflowContents;
  }
  const caseBody = `          case "$branch" in
            ${branchGuard}) ;;
            *) branch="${nonProductionBranch}" ;;
          esac`;
  return workflowContents.split(LEGACY_SCHEDULED_CHAOS_BRANCH_GUARD).join(caseBody);
}

function patchCleanupCacheBranchGuard(workflowContents: string, branchGuard: string): string {
  if (!workflowContents.includes(LEGACY_CLEANUP_CACHE_BRANCH_GUARD)) {
    return workflowContents;
  }
  const caseBody =
    `                case "$WF_RUN_BRANCH" in\n` +
    `                  ${branchGuard})\n` +
    '                    mode="lru"\n' +
    '                    if [ "$WF_RUN_CONCLUSION" = "failure" ]; then\n' +
    '                      keep_count="${KEEP_FAILED_RUNS}"\n' +
    '                    fi\n' +
    '                    ;;\n' +
    '                esac';
  return workflowContents.split(LEGACY_CLEANUP_CACHE_BRANCH_GUARD).join(caseBody);
}

function patchCleanupGhcrPackageMatrix(
  workflowContents: string,
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  return workflowContents.replace(
    /(\s+package:\s*\n)(?:\s+- [^\n]+\n)+/,
    `$1          - ${snapshot.artifacts.apiImage}\n          - ${snapshot.artifacts.workerImage}\n`,
  );
}

function patchWorkflowFile(
  relativePath: string,
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const filePath = resolve(REPOSITORY_ROOT, '.github/workflows', relativePath);
  if (!existsSync(filePath)) {
    return '';
  }
  let contents = readFileSync(filePath, 'utf-8');
  contents = patchWorkflowBranches(contents, snapshot.git.protectedBranches);
  const productionEnvironment =
    snapshot.branchEnvironmentMap[snapshot.git.productionBranch] ?? 'production';
  const nonProductionEnvironment =
    snapshot.branchEnvironmentMap[snapshot.git.nonProductionBranch] ?? 'development';

  if (relativePath === 'post-merge-ci.yml') {
    contents = patchPostMergeExpressions(
      contents,
      snapshot.git.productionBranch,
      snapshot.git.nonProductionBranch,
      productionEnvironment,
      nonProductionEnvironment,
    );
  }
  if (
    relativePath === 'reusable-railway-deploy.yml' ||
    relativePath === 'scheduled-monthly-restore-rto.yml' ||
    relativePath === 'scheduled-weekly-restore-smoke.yml'
  ) {
    contents = patchDeployCaseBlocks(contents, snapshot.branchEnvironmentMap);
  }
  if (relativePath === 'scheduled-chaos.yml') {
    const branchGuard = snapshot.git.protectedBranches.join('|');
    contents = patchScheduledChaosBranchGuard(
      contents,
      branchGuard,
      snapshot.git.nonProductionBranch,
    );
  }
  if (relativePath === 'cleanup-cache.yml') {
    const branchGuard = snapshot.git.protectedBranches.join('|');
    contents = patchCleanupCacheBranchGuard(contents, branchGuard);
  }
  if (relativePath === 'reusable-vitest-postgres-redis.yml') {
    contents = contents.replace(
      /if \[ "\$\{\{ inputs\.target_branch \}\}" = "dev" \]; then/g,
      `if [ "\${{ inputs.target_branch }}" = "${snapshot.git.nonProductionBranch}" ]; then`,
    );
  }
  if (relativePath === 'post-release-backmerge.yml') {
    contents = contents.replace(/\bref: dev\b/g, `ref: ${snapshot.git.nonProductionBranch}`);
  }
  if (relativePath === 'scheduled-monthly-restore-rto.yml') {
    contents = contents.replace(
      /ensure Neon project core-be and branch names match git refs \(main\/dev\)/g,
      `ensure Neon project ${snapshot.slug} and branch names match git refs (${snapshot.git.protectedBranches.join('/')})`,
    );
  }
  if (relativePath === 'cleanup-ghcr.yml') {
    contents = patchCleanupGhcrPackageMatrix(contents, snapshot);
  }

  return contents;
}

function writeGeneratedFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, 'utf-8');
}

export function generateAllProjectIdentityArtifacts(options?: { checkOnly?: boolean }): boolean {
  const checkOnly = options?.checkOnly ?? false;
  const config = loadConfig();
  const snapshot = buildProjectIdentitySnapshot(config);

  const openApiTitle = `${snapshot.displayName} API`;
  const outputs: Array<{ path: string; contents: string }> = [
    { path: OUTPUT_PATHS.constants, contents: renderConstants(snapshot) },
    { path: OUTPUT_PATHS.compositeAction, contents: renderCompositeAction(snapshot) },
    { path: OUTPUT_PATHS.projectIdentityEnv, contents: renderProjectIdentityEnv(snapshot) },
    { path: OUTPUT_PATHS.branchMapShell, contents: renderBranchMapShell(snapshot) },
    { path: OUTPUT_PATHS.dockerBake, contents: renderDockerBake(snapshot) },
  ];
  const openApiLocaleEn = renderOpenApiLocale(OUTPUT_PATHS.openApiLocaleEn, openApiTitle);
  const openApiLocaleEs = renderOpenApiLocale(OUTPUT_PATHS.openApiLocaleEs, openApiTitle);
  if (openApiLocaleEn) {
    outputs.push({ path: OUTPUT_PATHS.openApiLocaleEn, contents: openApiLocaleEn });
  }
  if (openApiLocaleEs) {
    outputs.push({ path: OUTPUT_PATHS.openApiLocaleEs, contents: openApiLocaleEs });
  }

  let stale = false;
  for (const output of outputs) {
    const existing = existsSync(output.path) ? readFileSync(output.path, 'utf-8') : '';
    if (existing !== output.contents) {
      stale = true;
      if (!checkOnly) {
        writeGeneratedFile(output.path, output.contents);
        console.log(`Wrote ${output.path.replace(`${REPOSITORY_ROOT}/`, '')}`);
      }
    }
  }

  for (const workflowFile of WORKFLOW_FILES_TO_PATCH) {
    const filePath = resolve(REPOSITORY_ROOT, '.github/workflows', workflowFile);
    const existing = existsSync(filePath) ? readFileSync(filePath, 'utf-8') : '';
    const patched = patchWorkflowFile(workflowFile, snapshot);
    if (patched && existing !== patched) {
      stale = true;
      if (!checkOnly) {
        writeFileSync(filePath, patched, 'utf-8');
        console.log(`Patched .github/workflows/${workflowFile}`);
      }
    }
  }

  const workflowViolations = validateWorkflowLiteralsAgainstManifest({
    snapshot,
    projectRoot: REPOSITORY_ROOT,
  });
  if (workflowViolations.length > 0) {
    console.error('Workflow project-identity literal violations:');
    for (const violation of workflowViolations) {
      console.error(`  ${violation.file}: ${violation.detail}`);
    }
    return false;
  }

  if (checkOnly) {
    if (stale) {
      console.error(
        'Project identity artifacts are out of sync with tooling/setup/setup.config.json. Run: pnpm tool:generate-project-identity',
      );
      return false;
    }
    console.log('Project identity artifacts are up to date.');
    return true;
  }

  console.log(
    stale ? 'Project identity generation complete.' : 'Project identity artifacts are up to date.',
  );
  return true;
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const ok = generateAllProjectIdentityArtifacts({ checkOnly });
  if (!ok) {
    process.exit(1);
  }
}

const isMain =
  process.argv[1]?.endsWith('generate-project-identity.ts') ||
  process.argv[1]?.includes('generate-project-identity');

if (isMain) {
  main();
}
