/**
 * Generates project identity artifacts from tooling/setup/setup.config.json.
 *
 * Usage:
 *   pnpm tool:generate-project-identity
 *   pnpm tool:generate-project-identity:check
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadConfig } from '@tooling/setup/common/config.js';
import { buildProjectIdentitySnapshot } from './project-identity.util.js';
import {
  renderCodeowners,
  renderComposeContainerNames,
  renderPackageJson,
  renderProductionEnvironment,
  renderSonarProperties,
} from './repository-identity-artifacts.js';
import { scanProjectIdentityLiterals } from './validate-project-identity-literals.js';
import {
  applyTextRewrites,
  MCP_TEMPLATE_PATHS,
  mcpTemplateRules,
  TEXT_REWRITE_TARGETS,
} from './text-identity-rewrites.js';
import { validateWorkflowLiteralsAgainstManifest } from './validate-project-identity-workflows.js';

const REPOSITORY_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

const GENERATED_BANNER =
  '// GENERATED by pnpm tool:generate-project-identity — do not edit; change tooling/setup/setup.config.json instead.\n';

const OUTPUT_PATHS = {
  constants: resolve(REPOSITORY_ROOT, 'src/shared/constants/project-identity.constants.ts'),
  compositeAction: resolve(REPOSITORY_ROOT, '.github/actions/setup-project-identity/action.yml'),
  projectIdentityEnv: resolve(REPOSITORY_ROOT, '.github/project-identity.env'),
  branchMapShell: resolve(REPOSITORY_ROOT, '.github/generated/branch-environment-map.sh'),
  dockerBake: resolve(REPOSITORY_ROOT, 'docker-bake.hcl'),
  openApiLocaleEn: resolve(REPOSITORY_ROOT, 'src/shared/locales/en/openapi.json'),
  openApiLocaleEs: resolve(REPOSITORY_ROOT, 'src/shared/locales/es/openapi.json'),
  codeowners: resolve(REPOSITORY_ROOT, '.github/CODEOWNERS'),
} as const;

/**
 * Files that are RECONCILED rather than emitted: the generator rewrites only the
 * identity-bearing fields and preserves everything else the file owns.
 */
const RECONCILED_PATHS = {
  packageJson: resolve(REPOSITORY_ROOT, 'package.json'),
  sonarProperties: resolve(REPOSITORY_ROOT, 'sonar-project.properties'),
  productionEnvironment: resolve(REPOSITORY_ROOT, '.github/environments/production.json'),
  dockerCompose: resolve(REPOSITORY_ROOT, 'docker-compose.yml'),
  dockerComposeSonar: resolve(REPOSITORY_ROOT, 'docker-compose.sonar.yml'),
} as const;

const WORKFLOW_FILES_TO_PATCH = [
  'pr-ci.yml',
  'post-merge-ci.yml',
  'pr-docs-lane.yml',
  'reusable-docker-build-trivy.yml',
  'reusable-railway-deploy.yml',
  'scheduled-monthly-restore-rto.yml',
  'scheduled-weekly-restore-smoke.yml',
  'scheduled-chaos.yml',
  'cleanup-cache.yml',
  'cleanup-ghcr.yml',
  'reusable-vitest-postgres-redis.yml',
] as const;

const LEGACY_DEPLOY_CASE_BLOCK = `              main) echo "environment=production"  >> "$GITHUB_OUTPUT" ;;
              dev)  echo "environment=development" >> "$GITHUB_OUTPUT" ;;`;

const LEGACY_SCHEDULED_CHAOS_BRANCH_GUARD = `          if [ "$branch" != "main" ] && [ "$branch" != "dev" ]; then
            branch="dev"
          fi`;

const LEGACY_CLEANUP_CACHE_BRANCH_GUARD =
  '                if [ "$WF_RUN_BRANCH" = "dev" ] || [ "$WF_RUN_BRANCH" = "main" ]; then\n' +
  '                  mode="lru"\n' +
  '                  if [ "$WF_RUN_CONCLUSION" = "failure" ]; then\n' +
  '                    keep_count="${KEEP_FAILED_RUNS}"\n' +
  '                  fi\n' +
  '                fi';

function renderConstants(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const { slug, displayName, artifacts, git, branchEnvironmentMap, repository, derived } = snapshot;
  const escapedDisplay = displayName.replace(/'/g, "\\'");
  return `${GENERATED_BANNER}
/** Canonical project slug (Neon, Sentry, JWT issuer, MCP URI scheme). */
export const PROJECT_SLUG = '${slug}';

/** GitHub \`owner/repo\` slug backing CODEOWNERS and environment reviewers. */
export const PROJECT_REPOSITORY = '${repository.slug}';

/** GitHub owner (user or organization login) that owns the repository. */
export const PROJECT_REPOSITORY_OWNER = '${repository.owner}';

/** Server name reported in the MCP handshake. */
export const API_SERVER_NAME = '${derived.apiServerName}';

/** \`User-Agent\` prefix on outbound webhook deliveries. */
export const WEBHOOK_USER_AGENT_PREFIX = '${derived.webhookUserAgent}';

/** Default Scalar registry slug when \`SCALAR_SLUG\` is unset. */
export const SCALAR_SLUG_DEFAULT = '${derived.scalarSlug}';

/** Postman collection name prefix (\`{displayName} API\`). */
export const POSTMAN_COLLECTION_PREFIX = '${derived.postmanCollectionPrefix.replace(/'/g, "\\'")}';

/** Repository-relative path of the generated DBML diagram. */
export const DBML_OUTPUT_PATH = '${derived.dbmlPath}';

/** JWT \`aud\` claim — changing this invalidates outstanding tokens. */
export const JWT_AUDIENCE = '${derived.jwtAudience}';

/** Local Postgres database, user and password for the \`compose:up\` stack. */
export const LOCAL_DATABASE_NAME = '${derived.databaseName}';

/** Redis key-prefix stem (\`<stem>:<NODE_ENV>:\`), isolating one product's keyspace. */
export const REDIS_KEY_PREFIX_STEM = '${derived.redisKeyPrefix}';

/** Restricted Postgres role the app connects as, under RLS. */
export const DATABASE_APP_ROLE = '${derived.databaseAppRole}';

/** Postgres role owning runtime objects. */
export const DATABASE_RUNTIME_ROLE = '${derived.databaseRuntimeRole}';

/** Human-facing product name for OpenAPI and emails. */
export const PROJECT_DISPLAY_NAME = '${escapedDisplay}';

/** Default OpenAPI \`info.title\` when locale strings omit a title. */
export const PROJECT_OPENAPI_TITLE = '${escapedDisplay} API';

/** JWT \`iss\` claim — changing this invalidates outstanding tokens. */
export const JWT_ISSUER = PROJECT_SLUG;

/** TOTP issuer shown in authenticator apps. */
export const TOTP_ISSUER = PROJECT_SLUG;

/** WebAuthn RP display name when \`WEBAUTHN_RP_NAME\` is unset. */
export const WEBAUTHN_RP_NAME_DEFAULT = PROJECT_SLUG;

/** MCP resource URI scheme prefix (\`{slug}://\`). */
export const MCP_URI_SCHEME = '${slug}';

/** MCP resource URI for the bundled OpenAPI document. */
export const MCP_OPENAPI_RESOURCE_URI = '${slug}://openapi';

/** MCP resource URI for the route catalog. */
export const MCP_ROUTES_RESOURCE_URI = '${slug}://routes';

/** OpenTelemetry service name for the API process. */
export const OTEL_SERVICE_NAME_API = '${artifacts.apiImage}';

/** OpenTelemetry service name for the worker process. */
export const OTEL_SERVICE_NAME_WORKER = '${artifacts.workerImage}';

/** OpenTelemetry tracer instrumentation scope name. */
export const OTEL_TRACER_NAME = PROJECT_SLUG;

/** Local Docker image tag for API smoke and PR verify builds. */
export const DOCKER_LOCAL_API_TAG = '${artifacts.dockerLocalApiTag}';

/** Local Docker image tag for worker images in compose and CI. */
export const DOCKER_LOCAL_WORKER_TAG = '${artifacts.workerImage}';

/** GHCR image repository name for the API container. */
export const GHCR_API_IMAGE_NAME = '${artifacts.apiImage}';

/** GHCR image repository name for the worker container. */
export const GHCR_WORKER_IMAGE_NAME = '${artifacts.workerImage}';

/** GHCR Actions cache scope key for API image layers. */
export const GHCR_CACHE_SCOPE_API = '${artifacts.ghcrCacheScopeApi}';

/** GHCR Actions cache scope key for worker image layers. */
export const GHCR_CACHE_SCOPE_WORKER = '${artifacts.ghcrCacheScopeWorker}';

/** Git branches that receive protected CI + deploy pipelines. */
export const PROTECTED_GIT_BRANCHES = [${[...git.protectedBranches].map((branch) => `'${branch}'`).join(', ')}] as const;

/** Default git branch (repository trunk) for new clones and PR bases; from setup.config.json git.defaultBranch. */
export const GIT_DEFAULT_BRANCH = '${git.defaultBranch}';

/** Production deploy branch (maps to production GitHub Environment). */
export const GIT_PRODUCTION_BRANCH = '${git.productionBranch}';

/** Non-production deploy branch (maps to development GitHub Environment). */
export const GIT_NON_PRODUCTION_BRANCH = '${git.nonProductionBranch}';

/** Maps git branch ref → hosted environment name (GitHub Environment / NODE_ENV). */
export const BRANCH_TO_ENVIRONMENT_MAP: Readonly<Record<string, string>> = {
${Object.entries(branchEnvironmentMap)
  .map(([branch, environment]) => `  ${branch}: '${environment}',`)
  .join('\n')}
};
`;
}

function renderCompositeAction(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const { slug, displayName, artifacts, git, branchEnvironmentMap } = snapshot;
  const protectedBranchesJson = JSON.stringify([...git.protectedBranches]);
  const branchEnvMapJson = JSON.stringify(branchEnvironmentMap);
  const echoLines = [
    `        echo "PROJECT_SLUG=${slug}" >> "$GITHUB_ENV"`,
    `        echo "PROJECT_DISPLAY_NAME=${displayName}" >> "$GITHUB_ENV"`,
    `        echo "API_IMAGE=${artifacts.apiImage}" >> "$GITHUB_ENV"`,
    `        echo "WORKER_IMAGE=${artifacts.workerImage}" >> "$GITHUB_ENV"`,
    `        echo "DOCKER_LOCAL_API_TAG=${artifacts.dockerLocalApiTag}" >> "$GITHUB_ENV"`,
    `        echo "GHCR_CACHE_SCOPE_API=${artifacts.ghcrCacheScopeApi}" >> "$GITHUB_ENV"`,
    `        echo "GHCR_CACHE_SCOPE_WORKER=${artifacts.ghcrCacheScopeWorker}" >> "$GITHUB_ENV"`,
    `        echo "GIT_DEFAULT_BRANCH=${git.defaultBranch}" >> "$GITHUB_ENV"`,
    `        echo "GIT_PRODUCTION_BRANCH=${git.productionBranch}" >> "$GITHUB_ENV"`,
    `        echo "GIT_NON_PRODUCTION_BRANCH=${git.nonProductionBranch}" >> "$GITHUB_ENV"`,
    `        echo 'PROTECTED_BRANCHES_JSON=${protectedBranchesJson}' >> "$GITHUB_ENV"`,
    `        echo 'BRANCH_ENV_MAP_JSON=${branchEnvMapJson}' >> "$GITHUB_ENV"`,
  ].join('\n');
  return `# GENERATED by pnpm tool:generate-project-identity — do not edit; change tooling/setup/setup.config.json instead.
name: Setup Project Identity
description: Sets project identity environment variables for the current job.
runs:
  using: composite
  steps:
    - name: Set project identity env vars
      shell: bash
      run: |
${echoLines}
`;
}

function renderProjectIdentityEnv(
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const lines = [
    '# GENERATED by pnpm tool:generate-project-identity — do not edit.',
    '# CI workflows use the generated composite action .github/actions/setup-project-identity/action.yml.',
    '# This file is for local scripts, docs, and tooling reference — not loaded by GitHub Actions.',
    `PROJECT_SLUG=${snapshot.slug}`,
    `PROJECT_DISPLAY_NAME=${snapshot.displayName}`,
    `API_IMAGE=${snapshot.artifacts.apiImage}`,
    `WORKER_IMAGE=${snapshot.artifacts.workerImage}`,
    `DOCKER_LOCAL_API_TAG=${snapshot.artifacts.dockerLocalApiTag}`,
    `GHCR_CACHE_SCOPE_API=${snapshot.artifacts.ghcrCacheScopeApi}`,
    `GHCR_CACHE_SCOPE_WORKER=${snapshot.artifacts.ghcrCacheScopeWorker}`,
    `GIT_DEFAULT_BRANCH=${snapshot.git.defaultBranch}`,
    `GIT_PRODUCTION_BRANCH=${snapshot.git.productionBranch}`,
    `GIT_NON_PRODUCTION_BRANCH=${snapshot.git.nonProductionBranch}`,
    `PROTECTED_BRANCHES_JSON=${JSON.stringify([...snapshot.git.protectedBranches])}`,
    `BRANCH_ENV_MAP_JSON=${JSON.stringify(snapshot.branchEnvironmentMap)}`,
    '',
  ];
  return lines.join('\n');
}

function renderBranchMapShell(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const cases = Object.entries(snapshot.branchEnvironmentMap)
    .map(([branch, environment]) => `    ${branch}) echo "${environment}" ;;`)
    .join('\n');
  return `#!/usr/bin/env bash
# GENERATED by pnpm tool:generate-project-identity — do not edit.
set -euo pipefail

map_branch_to_environment() {
  local branch="\${1:?branch required}"
  case "$branch" in
${cases}
    *)
      echo "::error::Unsupported branch for environment mapping: $branch" >&2
      return 1
      ;;
  esac
}
`;
}

function renderOpenApiLocale(localePath: string, openApiTitle: string): string | undefined {
  if (!existsSync(localePath)) {
    return undefined;
  }
  const parsed = JSON.parse(readFileSync(localePath, 'utf-8')) as {
    info?: { title?: string; description?: string };
    [key: string]: unknown;
  };
  if (!parsed.info) {
    return undefined;
  }
  parsed.info.title = openApiTitle;
  return `${JSON.stringify(parsed, null, 2)}\n`;
}

function renderDockerBake(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const apiTag = snapshot.artifacts.dockerLocalApiTag;
  const workerTag = snapshot.artifacts.workerImage;
  return `group "default" {
  targets = ["api", "worker"]
}

target "_common" {
  context    = "."
  dockerfile = "Dockerfile"
  args = {
    NODE_VERSION = "24.18.1"
    PNPM_VERSION = "11.1.1"
  }
}

target "api" {
  inherits = ["_common"]
  target   = "api"
  args = {
    GENERATE_MCP_DOCS = "true"
  }
  tags = ["${apiTag}:latest"]
}

target "worker" {
  inherits = ["_common"]
  target   = "worker"
  args = {
    GENERATE_MCP_DOCS = "false"
  }
  tags = ["${workerTag}:latest"]
}
`;
}

function patchWorkflowBranches(
  workflowContents: string,
  protectedBranches: readonly string[],
): string {
  const branchListYaml = protectedBranches.join(', ');
  let updated = workflowContents.replace(
    /branches:\s*\[[^\]]+\]/g,
    `branches: [${branchListYaml}]`,
  );
  updated = updated.replace(/fromJSON\('\[[^\]]+\]'\)/g, 'fromJSON(env.PROTECTED_BRANCHES_JSON)');
  return updated;
}

function patchPostMergeExpressions(
  workflowContents: string,
  productionBranch: string,
  nonProductionBranch: string,
  productionEnvironment: string,
  nonProductionEnvironment: string,
): string {
  return workflowContents
    .replace(
      /github\.ref_name == 'main' && 'production' \|\| 'development'/g,
      `github.ref_name == '${productionBranch}' && '${productionEnvironment}' || '${nonProductionEnvironment}'`,
    )
    .replace(
      /github\.ref_name == 'dev' && '\.dev' \|\| ''/g,
      `github.ref_name == '${nonProductionBranch}' && '.dev' || ''`,
    );
}

function patchDeployCaseBlocks(
  workflowContents: string,
  branchEnvironmentMap: Record<string, string>,
): string {
  if (!workflowContents.includes(LEGACY_DEPLOY_CASE_BLOCK)) {
    return workflowContents;
  }
  const caseBody = Object.entries(branchEnvironmentMap)
    .map(
      ([branch, environment]) =>
        `              ${branch}) echo "environment=${environment}"  >> "$GITHUB_OUTPUT" ;;`,
    )
    .join('\n');
  return workflowContents.split(LEGACY_DEPLOY_CASE_BLOCK).join(caseBody);
}

function patchScheduledChaosBranchGuard(
  workflowContents: string,
  branchGuard: string,
  nonProductionBranch: string,
): string {
  if (!workflowContents.includes(LEGACY_SCHEDULED_CHAOS_BRANCH_GUARD)) {
    return workflowContents;
  }
  const caseBody = `          case "$branch" in
            ${branchGuard}) ;;
            *) branch="${nonProductionBranch}" ;;
          esac`;
  return workflowContents.split(LEGACY_SCHEDULED_CHAOS_BRANCH_GUARD).join(caseBody);
}

function patchCleanupCacheBranchGuard(workflowContents: string, branchGuard: string): string {
  if (!workflowContents.includes(LEGACY_CLEANUP_CACHE_BRANCH_GUARD)) {
    return workflowContents;
  }
  const caseBody =
    `                case "$WF_RUN_BRANCH" in\n` +
    `                  ${branchGuard})\n` +
    '                    mode="lru"\n' +
    '                    if [ "$WF_RUN_CONCLUSION" = "failure" ]; then\n' +
    '                      keep_count="${KEEP_FAILED_RUNS}"\n' +
    '                    fi\n' +
    '                    ;;\n' +
    '                esac';
  return workflowContents.split(LEGACY_CLEANUP_CACHE_BRANCH_GUARD).join(caseBody);
}

function patchCleanupGhcrPackageMatrix(
  workflowContents: string,
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  return workflowContents.replace(
    /(\s+package:\s*\n)(?:\s+- [^\n]+\n)+/,
    `$1          - ${snapshot.artifacts.apiImage}\n          - ${snapshot.artifacts.workerImage}\n`,
  );
}

function patchWorkflowFile(
  relativePath: string,
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const filePath = resolve(REPOSITORY_ROOT, '.github/workflows', relativePath);
  if (!existsSync(filePath)) {
    return '';
  }
  let contents = readFileSync(filePath, 'utf-8');
  contents = patchWorkflowBranches(contents, snapshot.git.protectedBranches);
  const productionEnvironment =
    snapshot.branchEnvironmentMap[snapshot.git.productionBranch] ?? 'production';
  const nonProductionEnvironment =
    snapshot.branchEnvironmentMap[snapshot.git.nonProductionBranch] ?? 'development';

  if (relativePath === 'post-merge-ci.yml') {
    contents = patchPostMergeExpressions(
      contents,
      snapshot.git.productionBranch,
      snapshot.git.nonProductionBranch,
      productionEnvironment,
      nonProductionEnvironment,
    );
  }
  if (
    relativePath === 'reusable-railway-deploy.yml' ||
    relativePath === 'scheduled-monthly-restore-rto.yml' ||
    relativePath === 'scheduled-weekly-restore-smoke.yml'
  ) {
    contents = patchDeployCaseBlocks(contents, snapshot.branchEnvironmentMap);
  }
  if (relativePath === 'scheduled-chaos.yml') {
    const branchGuard = snapshot.git.protectedBranches.join('|');
    contents = patchScheduledChaosBranchGuard(
      contents,
      branchGuard,
      snapshot.git.nonProductionBranch,
    );
  }
  if (relativePath === 'cleanup-cache.yml') {
    const branchGuard = snapshot.git.protectedBranches.join('|');
    contents = patchCleanupCacheBranchGuard(contents, branchGuard);
  }
  if (relativePath === 'reusable-vitest-postgres-redis.yml') {
    contents = contents.replace(
      /if \[ "\$\{\{ inputs\.target_branch \}\}" = "dev" \]; then/g,
      `if [ "\${{ inputs.target_branch }}" = "${snapshot.git.nonProductionBranch}" ]; then`,
    );
  }
  if (relativePath === 'scheduled-monthly-restore-rto.yml') {
    // Match the SHAPE of the sentence, not the current slug/branches. Anchoring
    // on the literal values makes the rewrite self-disabling: after the first
    // rename the pattern no longer matches and the message silently goes stale.
    contents = contents.replace(
      /ensure Neon project \S+ and branch names match git refs \([^)]*\)/g,
      `ensure Neon project ${snapshot.slug} and branch names match git refs (${snapshot.git.protectedBranches.join('/')})`,
    );
  }
  if (relativePath === 'cleanup-ghcr.yml') {
    contents = patchCleanupGhcrPackageMatrix(contents, snapshot);
  }

  return contents;
}

function writeGeneratedFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, 'utf-8');
}

/**
 * Run Biome over the files this run wrote, so generation leaves a lint-clean tree.
 *
 * @remarks
 * `JSON.stringify(value, null, 2)` and Biome disagree on array wrapping, so a
 * freshly adopted project would otherwise fail `pnpm lint` on its own generated
 * manifest — the first gate an adopting team runs. Formatting here rather than
 * hand-matching Biome's output keeps the renderers simple and cannot drift when
 * the formatter's rules change.
 *
 * Best-effort: a missing or failing Biome must not fail generation, because the
 * identity rewrite itself succeeded and `pnpm lint` reports any residue anyway.
 */
function formatGeneratedFiles(paths: readonly string[]): void {
  const formattable = paths.filter((path) => /\.(json|ts|mjs)$/.test(path));
  if (formattable.length === 0) {
    return;
  }
  try {
    execFileSync('npx', ['biome', 'format', '--write', ...formattable], {
      cwd: REPOSITORY_ROOT,
      stdio: 'ignore',
    });
  } catch {
    console.warn('Could not run Biome on the generated files — run `pnpm format` if lint fails.');
  }
}

export function generateAllProjectIdentityArtifacts(options?: { checkOnly?: boolean }): boolean {
  const checkOnly = options?.checkOnly ?? false;
  const config = loadConfig();
  const snapshot = buildProjectIdentitySnapshot(config);

  const openApiTitle = `${snapshot.displayName} API`;
  const outputs: Array<{ path: string; contents: string }> = [
    { path: OUTPUT_PATHS.constants, contents: renderConstants(snapshot) },
    { path: OUTPUT_PATHS.compositeAction, contents: renderCompositeAction(snapshot) },
    { path: OUTPUT_PATHS.projectIdentityEnv, contents: renderProjectIdentityEnv(snapshot) },
    { path: OUTPUT_PATHS.branchMapShell, contents: renderBranchMapShell(snapshot) },
    { path: OUTPUT_PATHS.dockerBake, contents: renderDockerBake(snapshot) },
  ];
  const openApiLocaleEn = renderOpenApiLocale(OUTPUT_PATHS.openApiLocaleEn, openApiTitle);
  const openApiLocaleEs = renderOpenApiLocale(OUTPUT_PATHS.openApiLocaleEs, openApiTitle);
  if (openApiLocaleEn) {
    outputs.push({ path: OUTPUT_PATHS.openApiLocaleEn, contents: openApiLocaleEn });
  }
  if (openApiLocaleEs) {
    outputs.push({ path: OUTPUT_PATHS.openApiLocaleEs, contents: openApiLocaleEs });
  }
  outputs.push({ path: OUTPUT_PATHS.codeowners, contents: renderCodeowners(snapshot) });

  // A file may be touched by more than one rule (docker-compose.yml carries both
  // container names and the Toxiproxy image tag). Each transform must therefore
  // build on the PREVIOUS transform's result, not on a fresh read of the file —
  // otherwise the last writer silently discards every earlier rewrite.
  const reconciledContents = new Map<string, string>();
  const reconcile = (targetPath: string, render: (existing: string) => string): void => {
    if (!existsSync(targetPath)) {
      return;
    }
    const base = reconciledContents.get(targetPath) ?? readFileSync(targetPath, 'utf-8');
    reconciledContents.set(targetPath, render(base));
  };

  reconcile(RECONCILED_PATHS.packageJson, (existing) => renderPackageJson(snapshot, existing));
  reconcile(RECONCILED_PATHS.sonarProperties, (existing) =>
    renderSonarProperties(snapshot, existing),
  );
  reconcile(RECONCILED_PATHS.productionEnvironment, (existing) =>
    renderProductionEnvironment(snapshot, existing),
  );
  reconcile(RECONCILED_PATHS.dockerCompose, (existing) =>
    renderComposeContainerNames(snapshot, existing),
  );
  reconcile(RECONCILED_PATHS.dockerComposeSonar, (existing) =>
    renderComposeContainerNames(snapshot, existing),
  );

  // Files naming the project in free text (comments, titles, config keys, shell
  // commands). Shape-matched spans rather than whole-file templates — see
  // text-identity-rewrites.ts for why the patterns never reference the slug.
  for (const target of TEXT_REWRITE_TARGETS) {
    reconcile(resolve(REPOSITORY_ROOT, target.path), (existing) =>
      applyTextRewrites(existing, target.rules, snapshot),
    );
  }

  // MCP templates are pinned as exact mirrors by the mcp-config global test, so
  // one shared rule set drives all three rather than three drifting entries.
  for (const mcpPath of MCP_TEMPLATE_PATHS) {
    reconcile(resolve(REPOSITORY_ROOT, mcpPath), (existing) =>
      applyTextRewrites(existing, mcpTemplateRules(), snapshot),
    );
  }

  for (const [path, contents] of reconciledContents) {
    outputs.push({ path, contents });
  }

  let stale = false;
  const writtenPaths: string[] = [];
  for (const output of outputs) {
    const existing = existsSync(output.path) ? readFileSync(output.path, 'utf-8') : '';
    if (existing !== output.contents) {
      stale = true;
      if (!checkOnly) {
        writeGeneratedFile(output.path, output.contents);
        writtenPaths.push(output.path);
        console.log(`Wrote ${output.path.replace(`${REPOSITORY_ROOT}/`, '')}`);
      }
    }
  }
  formatGeneratedFiles(writtenPaths);

  for (const workflowFile of WORKFLOW_FILES_TO_PATCH) {
    const filePath = resolve(REPOSITORY_ROOT, '.github/workflows', workflowFile);
    const existing = existsSync(filePath) ? readFileSync(filePath, 'utf-8') : '';
    const patched = patchWorkflowFile(workflowFile, snapshot);
    if (patched && existing !== patched) {
      stale = true;
      if (!checkOnly) {
        writeFileSync(filePath, patched, 'utf-8');
        console.log(`Patched .github/workflows/${workflowFile}`);
      }
    }
  }

  const workflowViolations = validateWorkflowLiteralsAgainstManifest({
    snapshot,
    projectRoot: REPOSITORY_ROOT,
  });
  if (workflowViolations.length > 0) {
    console.error('Workflow project-identity literal violations:');
    for (const violation of workflowViolations) {
      console.error(`  ${violation.file}: ${violation.detail}`);
    }
    return false;
  }

  // Generator targets are exempt by construction: pass the paths this run owns
  // rather than restating them in the scanner, so the two cannot drift.
  const generatedPaths = [
    ...Object.values(OUTPUT_PATHS),
    ...Object.values(RECONCILED_PATHS),
    ...TEXT_REWRITE_TARGETS.map((target) => resolve(REPOSITORY_ROOT, target.path)),
    ...MCP_TEMPLATE_PATHS.map((path) => resolve(REPOSITORY_ROOT, path)),
    ...WORKFLOW_FILES_TO_PATCH.map((file) => resolve(REPOSITORY_ROOT, '.github/workflows', file)),
  ];
  const { violations, staleAllowances } = scanProjectIdentityLiterals({
    snapshot,
    projectRoot: REPOSITORY_ROOT,
    generatedPaths,
  });
  if (violations.length > 0) {
    console.error(
      `Hardcoded project-identity literals found (${violations.length}). Import the generated constants from src/shared/constants/project-identity.constants.ts, or read the manifest in tooling/:`,
    );
    for (const violation of violations) {
      console.error(
        `  ${violation.file}:${violation.line}  [${violation.literal}]  ${violation.text}`,
      );
    }
    return false;
  }
  if (staleAllowances.length > 0) {
    console.error(
      'Stale entries in IDENTITY_LITERAL_ALLOWLIST — the literal is gone, so remove the entry:',
    );
    for (const allowance of staleAllowances) {
      console.error(`  ${allowance.file} — ${allowance.reason}`);
    }
    return false;
  }

  if (checkOnly) {
    if (stale) {
      console.error(
        'Project identity artifacts are out of sync with tooling/setup/setup.config.json. Run: pnpm tool:generate-project-identity',
      );
      return false;
    }
    console.log('Project identity artifacts are up to date.');
    return true;
  }

  console.log(
    stale ? 'Project identity generation complete.' : 'Project identity artifacts are up to date.',
  );
  return true;
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const ok = generateAllProjectIdentityArtifacts({ checkOnly });
  if (!ok) {
    process.exit(1);
  }
}

const isMain =
  process.argv[1]?.endsWith('generate-project-identity.ts') ||
  process.argv[1]?.includes('generate-project-identity');

if (isMain) {
  main();
}
