/**
 * Generates project identity artifacts from tooling/setup/setup.config.json.
 *
 * Usage:
 *   pnpm tool:generate-project-identity
 *   pnpm tool:generate-project-identity:check
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadConfig } from '../common/config.js';
import { buildProjectIdentitySnapshot } from './project-identity.util.js';

const REPOSITORY_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

const GENERATED_BANNER =
  '// GENERATED by pnpm tool:generate-project-identity — do not edit; change tooling/setup/setup.config.json instead.\n';

const IDENTITY_ENV_BEGIN = '# BEGIN GENERATED project-identity';
const IDENTITY_ENV_END = '# END GENERATED project-identity';

const OUTPUT_PATHS = {
  constants: resolve(REPOSITORY_ROOT, 'src/shared/constants/project-identity.constants.ts'),
  syncConfig: resolve(REPOSITORY_ROOT, '.github/sync.config.json'),
  projectIdentityEnv: resolve(REPOSITORY_ROOT, '.github/project-identity.env'),
  branchMapShell: resolve(REPOSITORY_ROOT, '.github/generated/branch-environment-map.sh'),
  dockerBake: resolve(REPOSITORY_ROOT, 'docker-bake.hcl'),
} as const;

const WORKFLOW_FILES_TO_PATCH = [
  'pr-ci.yml',
  'post-merge-ci.yml',
  'pr-docs-lane.yml',
  'reusable-docker-build-trivy.yml',
  'reusable-railway-deploy.yml',
  'scheduled-monthly-restore-rto.yml',
  'scheduled-weekly-restore-smoke.yml',
  'scheduled-chaos.yml',
  'cleanup-cache.yml',
  'cleanup-ghcr.yml',
  'bootstrap-railway-service.yml',
  'post-release-backmerge.yml',
  'reusable-vitest-postgres-redis.yml',
] as const;

const LEGACY_DEPLOY_CASE_BLOCK = `              main) echo "environment=production"  >> "$GITHUB_OUTPUT" ;;
              dev)  echo "environment=development" >> "$GITHUB_OUTPUT" ;;`;

function renderConstants(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const { slug, displayName, artifacts, git, branchEnvironmentMap } = snapshot;
  const escapedDisplay = displayName.replace(/'/g, "\\'");
  return `${GENERATED_BANNER}
/** Canonical project slug (Neon, Sentry, JWT issuer, MCP URI scheme). */
export const PROJECT_SLUG = '${slug}' as const;

/** Human-facing product name for OpenAPI and emails. */
export const PROJECT_DISPLAY_NAME = '${escapedDisplay}' as const;

/** Default OpenAPI \`info.title\` when locale strings omit a title. */
export const PROJECT_OPENAPI_TITLE = '${escapedDisplay} API' as const;

/** JWT \`iss\` claim — changing this invalidates outstanding tokens. */
export const JWT_ISSUER = PROJECT_SLUG;

/** TOTP issuer shown in authenticator apps. */
export const TOTP_ISSUER = PROJECT_SLUG;

/** WebAuthn RP display name when \`WEBAUTHN_RP_NAME\` is unset. */
export const WEBAUTHN_RP_NAME_DEFAULT = PROJECT_SLUG;

/** MCP resource URI scheme prefix (\`{slug}://\`). */
export const MCP_URI_SCHEME = '${slug}' as const;

/** MCP resource URI for the bundled OpenAPI document. */
export const MCP_OPENAPI_RESOURCE_URI = '${slug}://openapi' as const;

/** MCP resource URI for the route catalog. */
export const MCP_ROUTES_RESOURCE_URI = '${slug}://routes' as const;

/** OpenTelemetry service name for the API process. */
export const OTEL_SERVICE_NAME_API = '${artifacts.apiImage}' as const;

/** OpenTelemetry service name for the worker process. */
export const OTEL_SERVICE_NAME_WORKER = '${artifacts.workerImage}' as const;

/** OpenTelemetry tracer instrumentation scope name. */
export const OTEL_TRACER_NAME = PROJECT_SLUG;

/** Local Docker image tag for API smoke and PR verify builds. */
export const DOCKER_LOCAL_API_TAG = '${artifacts.dockerLocalApiTag}' as const;

/** Local Docker image tag for worker images in compose and CI. */
export const DOCKER_LOCAL_WORKER_TAG = '${artifacts.workerImage}' as const;

/** GHCR image repository name for the API container. */
export const GHCR_API_IMAGE_NAME = '${artifacts.apiImage}' as const;

/** GHCR image repository name for the worker container. */
export const GHCR_WORKER_IMAGE_NAME = '${artifacts.workerImage}' as const;

/** GHCR Actions cache scope key for API image layers. */
export const GHCR_CACHE_SCOPE_API = '${artifacts.ghcrCacheScopeApi}' as const;

/** GHCR Actions cache scope key for worker image layers. */
export const GHCR_CACHE_SCOPE_WORKER = '${artifacts.ghcrCacheScopeWorker}' as const;

/** Git branches that receive protected CI + deploy pipelines. */
export const PROTECTED_GIT_BRANCHES = ${JSON.stringify([...git.protectedBranches])} as const;

/** Default git branch for new clones and PR bases (typically \`dev\`). */
export const GIT_DEFAULT_BRANCH = '${git.defaultBranch}' as const;

/** Production deploy branch (maps to production GitHub Environment). */
export const GIT_PRODUCTION_BRANCH = '${git.productionBranch}' as const;

/** Non-production deploy branch (maps to development GitHub Environment). */
export const GIT_NON_PRODUCTION_BRANCH = '${git.nonProductionBranch}' as const;

/** Maps git branch ref → hosted environment name (GitHub Environment / NODE_ENV). */
export const BRANCH_TO_ENVIRONMENT_MAP: Readonly<Record<string, string>> = ${JSON.stringify(branchEnvironmentMap, null, 2)};
`;
}

function renderSyncConfig(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  return `${JSON.stringify(
    {
      environments: snapshot.environments.map((environment) => ({
        name: environment.name,
        branch: environment.branch,
      })),
    },
    null,
    2,
  )}\n`;
}

function renderProjectIdentityEnv(
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const lines = [
    '# GENERATED by pnpm tool:generate-project-identity — do not edit.',
    '# CI workflows use the job-level env block (# BEGIN GENERATED project-identity) in .github/workflows/*.yml.',
    '# This file is for local scripts, docs, and tooling reference — not loaded by GitHub Actions.',
    `PROJECT_SLUG=${snapshot.slug}`,
    `PROJECT_DISPLAY_NAME=${snapshot.displayName}`,
    `API_IMAGE=${snapshot.artifacts.apiImage}`,
    `WORKER_IMAGE=${snapshot.artifacts.workerImage}`,
    `DOCKER_LOCAL_API_TAG=${snapshot.artifacts.dockerLocalApiTag}`,
    `GHCR_CACHE_SCOPE_API=${snapshot.artifacts.ghcrCacheScopeApi}`,
    `GHCR_CACHE_SCOPE_WORKER=${snapshot.artifacts.ghcrCacheScopeWorker}`,
    `GIT_DEFAULT_BRANCH=${snapshot.git.defaultBranch}`,
    `GIT_PRODUCTION_BRANCH=${snapshot.git.productionBranch}`,
    `GIT_NON_PRODUCTION_BRANCH=${snapshot.git.nonProductionBranch}`,
    `PROTECTED_BRANCHES_JSON=${JSON.stringify([...snapshot.git.protectedBranches])}`,
    `BRANCH_ENV_MAP_JSON=${JSON.stringify(snapshot.branchEnvironmentMap)}`,
    '',
  ];
  return lines.join('\n');
}

function renderBranchMapShell(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const cases = Object.entries(snapshot.branchEnvironmentMap)
    .map(([branch, environment]) => `    ${branch}) echo "${environment}" ;;`)
    .join('\n');
  return `#!/usr/bin/env bash
# GENERATED by pnpm tool:generate-project-identity — do not edit.
set -euo pipefail

map_branch_to_environment() {
  local branch="\${1:?branch required}"
  case "$branch" in
${cases}
    *)
      echo "::error::Unsupported branch for environment mapping: $branch" >&2
      return 1
      ;;
  esac
}
`;
}

function renderDockerBake(snapshot: ReturnType<typeof buildProjectIdentitySnapshot>): string {
  const apiTag = snapshot.artifacts.dockerLocalApiTag;
  const workerTag = snapshot.artifacts.workerImage;
  return `group "default" {
  targets = ["api", "worker"]
}

target "_common" {
  context    = "."
  dockerfile = "Dockerfile"
  args = {
    NODE_VERSION = "24.13.0"
    PNPM_VERSION = "11.1.1"
  }
}

target "api" {
  inherits = ["_common"]
  target   = "api"
  args = {
    GENERATE_MCP_DOCS = "true"
  }
  tags = ["${apiTag}:latest"]
}

target "worker" {
  inherits = ["_common"]
  target   = "worker"
  args = {
    GENERATE_MCP_DOCS = "false"
  }
  tags = ["${workerTag}:latest"]
}
`;
}

function renderIdentityJobEnvBlock(
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  return `      ${IDENTITY_ENV_BEGIN}
      PROJECT_SLUG: ${snapshot.slug}
      PROJECT_DISPLAY_NAME: ${snapshot.displayName}
      API_IMAGE: ${snapshot.artifacts.apiImage}
      WORKER_IMAGE: ${snapshot.artifacts.workerImage}
      DOCKER_LOCAL_API_TAG: ${snapshot.artifacts.dockerLocalApiTag}
      GHCR_CACHE_SCOPE_API: ${snapshot.artifacts.ghcrCacheScopeApi}
      GHCR_CACHE_SCOPE_WORKER: ${snapshot.artifacts.ghcrCacheScopeWorker}
      GIT_DEFAULT_BRANCH: ${snapshot.git.defaultBranch}
      GIT_PRODUCTION_BRANCH: ${snapshot.git.productionBranch}
      GIT_NON_PRODUCTION_BRANCH: ${snapshot.git.nonProductionBranch}
      PROTECTED_BRANCHES_JSON: '${JSON.stringify([...snapshot.git.protectedBranches])}'
      BRANCH_ENV_MAP_JSON: '${JSON.stringify(snapshot.branchEnvironmentMap)}'
      ${IDENTITY_ENV_END}`;
}

function injectIdentityJobEnvBlock(
  workflowContents: string,
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const identityBlock = renderIdentityJobEnvBlock(snapshot);
  const identityBlockPattern = new RegExp(
    `      ${IDENTITY_ENV_BEGIN.replace('#', '\\#')}[\\s\\S]*?      ${IDENTITY_ENV_END.replace('#', '\\#')}\\n`,
    'g',
  );

  const needsIdentityEnv =
    /\$\{\{\s*env\.(DOCKER_LOCAL_API_TAG|API_IMAGE|WORKER_IMAGE|GHCR_CACHE_SCOPE_API|GHCR_CACHE_SCOPE_WORKER|PROTECTED_BRANCHES_JSON)\s*\}\}/.test(
      workflowContents,
    ) || /fromJSON\(env\.PROTECTED_BRANCHES_JSON\)/.test(workflowContents);

  if (!needsIdentityEnv) {
    return workflowContents;
  }

  if (workflowContents.includes(IDENTITY_ENV_BEGIN)) {
    return workflowContents.replace(identityBlockPattern, `${identityBlock}\n`);
  }

  return workflowContents.replace(/(^ {4}env:\n)/gm, `$1${identityBlock}\n`);
}

function patchWorkflowBranches(
  workflowContents: string,
  protectedBranches: readonly string[],
): string {
  const branchListYaml = protectedBranches.join(', ');
  let updated = workflowContents.replace(
    /branches:\s*\[[^\]]+\]/g,
    `branches: [${branchListYaml}]`,
  );
  updated = updated.replace(/fromJSON\('\[[^\]]+\]'\)/g, 'fromJSON(env.PROTECTED_BRANCHES_JSON)');
  return updated;
}

function patchPostMergeExpressions(
  workflowContents: string,
  productionBranch: string,
  nonProductionBranch: string,
  productionEnvironment: string,
  nonProductionEnvironment: string,
): string {
  return workflowContents
    .replace(
      /github\.ref_name == 'main' && 'production' \|\| 'development'/g,
      `github.ref_name == '${productionBranch}' && '${productionEnvironment}' || '${nonProductionEnvironment}'`,
    )
    .replace(
      /github\.ref_name == 'dev' && '\.dev' \|\| ''/g,
      `github.ref_name == '${nonProductionBranch}' && '.dev' || ''`,
    );
}

function patchDeployCaseBlocks(
  workflowContents: string,
  branchEnvironmentMap: Record<string, string>,
): string {
  if (!workflowContents.includes(LEGACY_DEPLOY_CASE_BLOCK)) {
    return workflowContents;
  }
  const caseBody = Object.entries(branchEnvironmentMap)
    .map(
      ([branch, environment]) =>
        `              ${branch}) echo "environment=${environment}"  >> "$GITHUB_OUTPUT" ;;`,
    )
    .join('\n');
  return workflowContents.split(LEGACY_DEPLOY_CASE_BLOCK).join(caseBody);
}

function patchWorkflowDockerArtifacts(
  workflowContents: string,
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const { artifacts } = snapshot;
  const apiTag = artifacts.dockerLocalApiTag;
  const workerTag = artifacts.workerImage;
  const apiImage = artifacts.apiImage;
  const workerImage = artifacts.workerImage;
  const cacheApi = artifacts.ghcrCacheScopeApi;
  const cacheWorker = artifacts.ghcrCacheScopeWorker;

  const updated = workflowContents
    .replaceAll(`tags: ${apiTag}:ci`, 'tags: ${{ env.DOCKER_LOCAL_API_TAG }}:ci')
    .replaceAll(`tags: ${apiTag}:pr-verify`, 'tags: ${{ env.DOCKER_LOCAL_API_TAG }}:pr-verify')
    .replaceAll(`tags: ${workerTag}:ci`, 'tags: ${{ env.WORKER_IMAGE }}:ci')
    .replaceAll(`tags: ${workerTag}:pr-verify`, 'tags: ${{ env.WORKER_IMAGE }}:pr-verify')
    .replaceAll(`image-ref: ${apiTag}:ci`, 'image-ref: ${{ env.DOCKER_LOCAL_API_TAG }}:ci')
    .replaceAll(`image-ref: ${workerTag}:ci`, 'image-ref: ${{ env.WORKER_IMAGE }}:ci')
    .replaceAll(`image: ${apiTag}:ci`, 'image: ${{ env.DOCKER_LOCAL_API_TAG }}:ci')
    .replaceAll(`image: ${workerTag}:ci`, 'image: ${{ env.WORKER_IMAGE }}:ci')
    .replaceAll(`docker run --rm ${workerTag}:ci`, 'docker run --rm ${{ env.WORKER_IMAGE }}:ci')
    .replaceAll(`docker tag ${apiTag}:ci`, 'docker tag ${{ env.DOCKER_LOCAL_API_TAG }}:ci')
    .replaceAll(`docker tag ${workerTag}:ci`, 'docker tag ${{ env.WORKER_IMAGE }}:ci')
    .replaceAll(`scope=${cacheApi}`, 'scope=${{ env.GHCR_CACHE_SCOPE_API }}')
    .replaceAll(`scope=${cacheWorker}`, 'scope=${{ env.GHCR_CACHE_SCOPE_WORKER }}')
    .replaceAll(`scope=${cacheApi}-pr`, 'scope=${{ env.GHCR_CACHE_SCOPE_API }}-pr')
    .replaceAll(`scope=${cacheWorker}-pr`, 'scope=${{ env.GHCR_CACHE_SCOPE_WORKER }}-pr')
    .replaceAll(
      `API_IMAGE="ghcr.io/\${{ github.repository }}/${apiImage}"`,
      'API_IMAGE="ghcr.io/${{ github.repository }}/${{ env.API_IMAGE }}"',
    )
    .replaceAll(
      `WORKER_IMAGE="ghcr.io/\${{ github.repository }}/${workerImage}"`,
      'WORKER_IMAGE="ghcr.io/${{ github.repository }}/${{ env.WORKER_IMAGE }}"',
    )
    .replaceAll(`ghcr.io/\${REPOSITORY}/${apiImage}`, 'ghcr.io/${REPOSITORY}/${{ env.API_IMAGE }}')
    .replaceAll(
      `ghcr.io/\${REPOSITORY}/${workerImage}`,
      'ghcr.io/${REPOSITORY}/${{ env.WORKER_IMAGE }}',
    )
    .replaceAll(`${apiTag}:ci node`, '${{ env.DOCKER_LOCAL_API_TAG }}:ci node')
    .replaceAll(`--name ${apiTag}-health`, '--name ${{ env.DOCKER_LOCAL_API_TAG }}-health')
    .replaceAll(
      `docker logs ${apiTag}-health`,
      'docker logs ${{ env.DOCKER_LOCAL_API_TAG }}-health',
    )
    .replaceAll(
      `docker rm -f ${apiTag}-health`,
      'docker rm -f ${{ env.DOCKER_LOCAL_API_TAG }}-health',
    )
    .replaceAll(
      `worker_image="\${IMAGE_OVERRIDE/${apiImage}/${workerImage}}"`,
      'worker_image="${IMAGE_OVERRIDE/${{ env.API_IMAGE }}/${{ env.WORKER_IMAGE }}}"',
    )
    .replaceAll(
      `ghcr.io/\${{ github.repository }}/${apiImage}:`,
      'ghcr.io/${{ github.repository }}/${{ env.API_IMAGE }}:',
    )
    .replaceAll(
      `ghcr.io/\${{ github.repository }}/${workerImage}:`,
      'ghcr.io/${{ github.repository }}/${{ env.WORKER_IMAGE }}:',
    );

  return injectIdentityJobEnvBlock(updated, snapshot);
}

function patchWorkflowFile(
  relativePath: string,
  snapshot: ReturnType<typeof buildProjectIdentitySnapshot>,
): string {
  const filePath = resolve(REPOSITORY_ROOT, '.github/workflows', relativePath);
  if (!existsSync(filePath)) {
    return '';
  }
  let contents = readFileSync(filePath, 'utf-8');
  contents = patchWorkflowBranches(contents, snapshot.git.protectedBranches);
  const productionEnvironment =
    snapshot.branchEnvironmentMap[snapshot.git.productionBranch] ?? 'production';
  const nonProductionEnvironment =
    snapshot.branchEnvironmentMap[snapshot.git.nonProductionBranch] ?? 'development';

  if (relativePath === 'post-merge-ci.yml') {
    contents = patchPostMergeExpressions(
      contents,
      snapshot.git.productionBranch,
      snapshot.git.nonProductionBranch,
      productionEnvironment,
      nonProductionEnvironment,
    );
  }
  if (
    relativePath === 'reusable-railway-deploy.yml' ||
    relativePath === 'scheduled-monthly-restore-rto.yml' ||
    relativePath === 'scheduled-weekly-restore-smoke.yml'
  ) {
    contents = patchDeployCaseBlocks(contents, snapshot.branchEnvironmentMap);
  }
  if (relativePath === 'scheduled-chaos.yml') {
    const branchGuard = snapshot.git.protectedBranches.join('|');
    contents = contents
      .replace(
        /if ! echo '\[[^\]]*\]' \| jq[^\n]+\n\s+branch="[^"]+"/g,
        `case "$branch" in\n            ${branchGuard}) ;;\n            *) branch="${snapshot.git.nonProductionBranch}" ;;\n          esac`,
      )
      .replace(
        /if \[ "\$branch" != "main" \] && \[ "\$branch" != "dev" \]; then\n\s+branch="dev"/g,
        `case "$branch" in\n            ${branchGuard}) ;;\n            *) branch="${snapshot.git.nonProductionBranch}" ;;\n          esac`,
      );
  }
  if (relativePath === 'cleanup-cache.yml') {
    const branchGuard = snapshot.git.protectedBranches.join('|');
    contents = contents
      .replace(
        /if echo '\[[^\]]*\]' \| jq[^\n]+; then/g,
        `case "$WF_RUN_BRANCH" in\n                  ${branchGuard})`,
      )
      .replace(
        /if \[ "\$WF_RUN_BRANCH" = "dev" \] \|\| \[ "\$WF_RUN_BRANCH" = "main" \]; then/g,
        `case "$WF_RUN_BRANCH" in\n                  ${branchGuard})`,
      );
  }
  if (relativePath === 'reusable-vitest-postgres-redis.yml') {
    contents = contents.replace(
      /if \[ "\$\{\{ inputs\.target_branch \}\}" = "dev" \]; then/g,
      `if [ "\${{ inputs.target_branch }}" = "${snapshot.git.nonProductionBranch}" ]; then`,
    );
  }
  if (relativePath === 'post-release-backmerge.yml') {
    contents = contents.replace(/\bref: dev\b/g, `ref: ${snapshot.git.nonProductionBranch}`);
  }
  if (relativePath === 'cleanup-ghcr.yml') {
    contents = contents
      .replaceAll(`- ${snapshot.artifacts.apiImage}`, '- ${{ env.API_IMAGE }}')
      .replaceAll(`- ${snapshot.artifacts.workerImage}`, '- ${{ env.WORKER_IMAGE }}');
    contents = injectIdentityJobEnvBlock(contents, snapshot);
  }

  const dockerWorkflows = new Set([
    'pr-ci.yml',
    'reusable-docker-build-trivy.yml',
    'reusable-railway-deploy.yml',
    'bootstrap-railway-service.yml',
    'cleanup-ghcr.yml',
  ]);
  if (dockerWorkflows.has(relativePath)) {
    contents = patchWorkflowDockerArtifacts(contents, snapshot);
  } else if (
    /\$\{\{\s*env\.(DOCKER_LOCAL_API_TAG|API_IMAGE|PROTECTED_BRANCHES_JSON)/.test(contents) ||
    /fromJSON\(env\.PROTECTED_BRANCHES_JSON\)/.test(contents)
  ) {
    contents = injectIdentityJobEnvBlock(contents, snapshot);
  }

  return contents;
}

function writeGeneratedFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, 'utf-8');
}

export function generateAllProjectIdentityArtifacts(options?: { checkOnly?: boolean }): boolean {
  const checkOnly = options?.checkOnly ?? false;
  const config = loadConfig();
  const snapshot = buildProjectIdentitySnapshot(config);

  const outputs: Array<{ path: string; contents: string }> = [
    { path: OUTPUT_PATHS.constants, contents: renderConstants(snapshot) },
    { path: OUTPUT_PATHS.syncConfig, contents: renderSyncConfig(snapshot) },
    { path: OUTPUT_PATHS.projectIdentityEnv, contents: renderProjectIdentityEnv(snapshot) },
    { path: OUTPUT_PATHS.branchMapShell, contents: renderBranchMapShell(snapshot) },
    { path: OUTPUT_PATHS.dockerBake, contents: renderDockerBake(snapshot) },
  ];

  let stale = false;
  for (const output of outputs) {
    const existing = existsSync(output.path) ? readFileSync(output.path, 'utf-8') : '';
    if (existing !== output.contents) {
      stale = true;
      if (!checkOnly) {
        writeGeneratedFile(output.path, output.contents);
        console.log(`Wrote ${output.path.replace(`${REPOSITORY_ROOT}/`, '')}`);
      }
    }
  }

  for (const workflowFile of WORKFLOW_FILES_TO_PATCH) {
    const filePath = resolve(REPOSITORY_ROOT, '.github/workflows', workflowFile);
    const existing = existsSync(filePath) ? readFileSync(filePath, 'utf-8') : '';
    const patched = patchWorkflowFile(workflowFile, snapshot);
    if (patched && existing !== patched) {
      stale = true;
      if (!checkOnly) {
        writeFileSync(filePath, patched, 'utf-8');
        console.log(`Patched .github/workflows/${workflowFile}`);
      }
    }
  }

  if (checkOnly) {
    if (stale) {
      console.error(
        'Project identity artifacts are out of sync with tooling/setup/setup.config.json. Run: pnpm tool:generate-project-identity',
      );
      return false;
    }
    console.log('Project identity artifacts are up to date.');
    return true;
  }

  console.log(
    stale ? 'Project identity generation complete.' : 'Project identity artifacts are up to date.',
  );
  return true;
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const ok = generateAllProjectIdentityArtifacts({ checkOnly });
  if (!ok) {
    process.exit(1);
  }
}

const isMain =
  process.argv[1]?.endsWith('generate-project-identity.ts') ||
  process.argv[1]?.includes('generate-project-identity');

if (isMain) {
  main();
}
