/**
 * Renderers for the repository-level files that carry project identity but are
 * not TypeScript: CODEOWNERS, the Sonar project descriptor, `package.json`
 * naming, and the production environment's reviewer roster.
 *
 * @remarks
 * These live outside `generate-project-identity.ts` because each one reconciles
 * an EXISTING hand-maintained file rather than emitting a file wholesale, and
 * the reconcile rules are where the correctness risk sits.
 *
 * Ownership boundary with `github:tool:governance-mode`: CODEOWNERS is the
 * reviewer roster and this module owns its identity. `production.json`'s
 * `preventSelfReview` and the ruleset parameters remain governance-mode's — this
 * module only rewrites reviewer HANDLES so they stay a subset of the roster, and
 * never changes the reviewer count or any mode-coupled field.
 */
import type { ProjectIdentitySnapshot } from './project-identity.util.js';

/**
 * CODEOWNERS path patterns, in file order. Repository STRUCTURE (not identity),
 * so it is a static list here; only the owner handles come from the manifest.
 */
const CODEOWNERS_SECTIONS: ReadonlyArray<{
  readonly heading: string;
  readonly patterns: readonly string[];
}> = [
  { heading: 'Default — all files', patterns: ['*'] },
  {
    heading: 'Domains',
    patterns: [
      '/src/domains/auth/',
      '/src/domains/billing/',
      '/src/domains/tenancy/',
      '/src/domains/user/',
      '/src/domains/notify/',
      '/src/domains/audit/',
      '/src/domains/upload/',
    ],
  },
  { heading: 'Infrastructure', patterns: ['/src/infrastructure/'] },
  { heading: 'Shared / middleware', patterns: ['/src/shared/'] },
  { heading: 'CI/CD', patterns: ['/.github/'] },
  { heading: 'Database', patterns: ['/migrations/', '/drizzle.config.ts'] },
  {
    heading: 'Scripts, docs, and tests',
    patterns: ['/tooling/', '/docs/', '/src/tests/'],
  },
  { heading: 'Tooling and editor', patterns: ['/.husky/', '/.vscode/'] },
  {
    heading: 'Container',
    patterns: [
      '/Dockerfile',
      '/Dockerfile.worker',
      '/Dockerfile.agent',
      '/docker-compose.yml',
      '/.dockerignore',
    ],
  },
  {
    heading: 'Root configuration',
    patterns: [
      '/package.json',
      '/pnpm-lock.yaml',
      '/tsconfig.json',
      '/vitest.config.ts',
      '/tooling/vitest/',
      '/biome.json',
      '/.biomeignore',
      '/.gitleaks.toml',
      '/.semgrepignore',
    ],
  },
];

/** Column at which owner handles are aligned, matching the committed file. */
const OWNER_COLUMN = 25;

/**
 * Render `.github/CODEOWNERS` from the manifest roster.
 *
 * @remarks
 * Handles are emitted `@`-prefixed. `providers.github.owners` supplies the
 * roster; it defaults to the owner segment of `providers.github.repository`,
 * which is correct for a personal repository. Add a second owner there before
 * running `pnpm github:tool:governance-mode team`, which requires ≥2.
 */
export function renderCodeowners(snapshot: ProjectIdentitySnapshot): string {
  const owners = snapshot.repository.owners.map((owner) => `@${owner}`).join(' ');
  const lines: string[] = [
    '# GENERATED by pnpm tool:generate-project-identity — do not edit;',
    '# change providers.github.owners in tooling/setup/setup.config.json instead.',
    '#',
    '# CODEOWNERS is the reviewer roster read by `pnpm github:tool:governance-mode`.',
    '# Team mode requires at least two distinct owners here.',
  ];
  for (const section of CODEOWNERS_SECTIONS) {
    lines.push('', `# ${section.heading}`);
    for (const pattern of section.patterns) {
      lines.push(`${pattern.padEnd(OWNER_COLUMN)}${owners}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

/** Render `sonar-project.properties` from the manifest-derived project key. */
export function renderSonarProperties(snapshot: ProjectIdentitySnapshot, existing: string): string {
  const { sonarProjectKey } = snapshot.derived;
  return existing
    .replace(/^sonar\.projectKey=.*$/m, `sonar.projectKey=${sonarProjectKey}`)
    .replace(/^sonar\.projectName=.*$/m, `sonar.projectName=${sonarProjectKey}`);
}

/**
 * Reconcile `package.json` identity fields against the manifest.
 *
 * @remarks
 * Rewrites `name` (from `project.packageName`, defaulting to the slug) and adds
 * `repository`/`bugs`/`homepage` derived from `providers.github.repository` so a
 * fork does not inherit the base project's coordinates. `description` is
 * rewritten only when the manifest sets one — the committed description is a
 * usable default and forcing adopters to invent one would block `init:project`.
 * Key order is preserved; renaming `name` requires a `pnpm install` to resync
 * the lockfile, which `init:project` performs.
 */
export function renderPackageJson(snapshot: ProjectIdentitySnapshot, existing: string): string {
  const parsed = JSON.parse(existing) as Record<string, unknown>;
  const repositoryUrl = `https://github.com/${snapshot.repository.slug}`;
  parsed.name = snapshot.packageName;
  if (snapshot.description) {
    parsed.description = snapshot.description;
  }
  parsed.repository = { type: 'git', url: `git+${repositoryUrl}.git` };
  parsed.bugs = { url: `${repositoryUrl}/issues` };
  parsed.homepage = `${repositoryUrl}#readme`;
  return `${JSON.stringify(parsed, null, 2)}\n`;
}

/**
 * Reconcile the production environment's reviewer handles against the roster.
 *
 * @remarks
 * Identity-only: any reviewer not present in `providers.github.owners` is
 * replaced by roster members, preserving the ORIGINAL reviewer COUNT so the
 * governance mode encoded by the file is unchanged. `preventSelfReview`,
 * `teams`, and the deployment branch policy are never touched — those belong to
 * `pnpm github:tool:governance-mode`, whose `--check` still validates the pair.
 */
export function renderProductionEnvironment(
  snapshot: ProjectIdentitySnapshot,
  existing: string,
): string {
  const parsed = JSON.parse(existing) as {
    protection?: { requiredReviewers?: { users?: string[] } };
  };
  const requiredReviewers = parsed.protection?.requiredReviewers;
  if (!(requiredReviewers && Array.isArray(requiredReviewers.users))) {
    return existing;
  }
  const roster = snapshot.repository.owners;
  const reconciled: string[] = [];
  for (const [index, user] of requiredReviewers.users.entries()) {
    if (roster.includes(user)) {
      reconciled.push(user);
      continue;
    }
    // Off-roster handle (a stale base-project owner after a fork): take the
    // roster member at the same position so the count — and therefore the
    // governance mode — is preserved.
    const replacement = roster[index] ?? roster[roster.length - 1];
    if (replacement && !reconciled.includes(replacement)) {
      reconciled.push(replacement);
    }
  }
  requiredReviewers.users = reconciled.length > 0 ? reconciled : [...roster].slice(0, 1);
  return `${JSON.stringify(parsed, null, 2)}\n`;
}

/**
 * Rewrite Docker Compose `container_name:` values to the slug-derived names.
 *
 * @remarks
 * Matches on the SERVICE SUFFIX (`-postgres`, `-redis`, …) rather than on the
 * current slug, so it stays correct across renames and is idempotent. Matching
 * on the old literal instead is a self-disabling pattern: the first rename makes
 * the search string unmatchable and the rewrite silently stops applying.
 */
export function renderComposeContainerNames(
  snapshot: ProjectIdentitySnapshot,
  existing: string,
): string {
  const { containers } = snapshot.derived;
  // Longest suffixes first: `-sonar-scanner` must win over a `-sonar*` prefix
  // match, and any future `-redis-*` service over `-redis`.
  const bySuffix: ReadonlyArray<readonly [string, string]> = [
    ['sonar-scanner', containers.sonarScanner],
    ['sonarqube', containers.sonarqube],
    ['toxiproxy', containers.toxiproxy],
    ['postgres', containers.postgres],
    ['redis', containers.redis],
  ];
  let updated = existing;
  for (const [suffix, containerName] of bySuffix) {
    updated = updated.replace(
      new RegExp(`^([ \\t]*container_name:[ \\t]*)\\S*-${escapeRegExp(suffix)}[ \\t]*$`, 'gm'),
      `$1${containerName}`,
    );
  }
  return updated;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
