// GENERATED by pnpm tool:generate-project-identity — do not edit; change tooling/setup/setup.config.json instead.

/** Canonical project slug (Neon, Sentry, JWT issuer, MCP URI scheme). */
export const PROJECT_SLUG = 'core-be';

/** Human-facing product name for OpenAPI and emails. */
export const PROJECT_DISPLAY_NAME = 'core-be';

/** Default OpenAPI `info.title` when locale strings omit a title. */
export const PROJECT_OPENAPI_TITLE = 'core-be API';

/** JWT `iss` claim — changing this invalidates outstanding tokens. */
export const JWT_ISSUER = PROJECT_SLUG;

/** TOTP issuer shown in authenticator apps. */
export const TOTP_ISSUER = PROJECT_SLUG;

/** WebAuthn RP display name when `WEBAUTHN_RP_NAME` is unset. */
export const WEBAUTHN_RP_NAME_DEFAULT = PROJECT_SLUG;

/** MCP resource URI scheme prefix (`{slug}://`). */
export const MCP_URI_SCHEME = 'core-be';

/** MCP resource URI for the bundled OpenAPI document. */
export const MCP_OPENAPI_RESOURCE_URI = 'core-be://openapi';

/** MCP resource URI for the route catalog. */
export const MCP_ROUTES_RESOURCE_URI = 'core-be://routes';

/** OpenTelemetry service name for the API process. */
export const OTEL_SERVICE_NAME_API = 'core-be-api';

/** OpenTelemetry service name for the worker process. */
export const OTEL_SERVICE_NAME_WORKER = 'core-be-worker';

/** OpenTelemetry tracer instrumentation scope name. */
export const OTEL_TRACER_NAME = PROJECT_SLUG;

/** Local Docker image tag for API smoke and PR verify builds. */
export const DOCKER_LOCAL_API_TAG = 'core-be';

/** Local Docker image tag for worker images in compose and CI. */
export const DOCKER_LOCAL_WORKER_TAG = 'core-be-worker';

/** GHCR image repository name for the API container. */
export const GHCR_API_IMAGE_NAME = 'core-be-api';

/** GHCR image repository name for the worker container. */
export const GHCR_WORKER_IMAGE_NAME = 'core-be-worker';

/** GHCR Actions cache scope key for API image layers. */
export const GHCR_CACHE_SCOPE_API = 'core-be-api';

/** GHCR Actions cache scope key for worker image layers. */
export const GHCR_CACHE_SCOPE_WORKER = 'core-be-worker';

/** Git branches that receive protected CI + deploy pipelines. */
export const PROTECTED_GIT_BRANCHES = ['main'] as const;

/** Default git branch for new clones and PR bases (typically `dev`). */
export const GIT_DEFAULT_BRANCH = 'main';

/** Production deploy branch (maps to production GitHub Environment). */
export const GIT_PRODUCTION_BRANCH = 'main';

/** Non-production deploy branch (maps to development GitHub Environment). */
export const GIT_NON_PRODUCTION_BRANCH = 'main';

/** Maps git branch ref → hosted environment name (GitHub Environment / NODE_ENV). */
export const BRANCH_TO_ENVIRONMENT_MAP: Readonly<Record<string, string>> = {
  main: 'production',
};
