import { describe, expect, it } from 'vitest';
import { buildSrcStructureTree } from '@/scripts/codegen/generate-project-structure-tree.js';
import { SRC_ROOT } from '@/scripts/codegen/project-structure-tree.constants.js';

describe('generate-project-structure-tree', () => {
  it('includes domains/auth in committed tree output', () => {
    const content = buildSrcStructureTree({ includeTests: true });
    expect(content).toContain(`${SRC_ROOT}/`);
    expect(content).toContain('├── domains/');
    expect(content).toContain('# Generated by pnpm tool:project-structure-tree');
  });

  it('stdout mode skips __tests__ directories', () => {
    const content = buildSrcStructureTree({ includeTests: false });
    const treeLines = content.split('\n').filter((line) => !line.startsWith('#'));
    expect(treeLines.some((line) => line.includes('__tests__/'))).toBe(false);
    expect(content).toContain('domains/');
  });
});
