/**
 * Writes .env.<environmentName> files at project root with values from provisioned state.
 * Use these files to push secrets to GitHub Environment secrets (e.g. gh secret set --env dev).
 * Structure and key order follow .env.example for easy reference.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadConfig, getEnvironmentNames } from './config.js';
import { loadSecrets } from './secrets.js';
import { loadState } from './state.js';
import { buildEnvironmentVariables } from './build-env-vars.js';
import * as logger from './logger.util.js';
import type { EnvironmentVariables } from './types.js';

const PROJECT_ROOT = resolve(import.meta.dirname, '../../');

/** Section headers and keys in display order (matches .env.example). */
const ENV_SECTIONS: Array<{ comment: string; keys: (keyof EnvironmentVariables)[] }> = [
  { comment: 'Server', keys: ['PORT', 'HOST', 'NODE_ENV', 'LOG_LEVEL'] },
  { comment: 'Database (managed service)', keys: ['DATABASE_URL'] },
  {
    comment: 'Redis (shared cache, rate limits, idempotency, BullMQ)',
    keys: ['REDIS_URL'],
  },
  { comment: 'Auth (JWT_SECRET must be at least 32 characters)', keys: ['JWT_SECRET'] },
  { comment: 'CORS', keys: ['ALLOWED_ORIGINS'] },
  { comment: 'App URLs', keys: ['FRONTEND_URL'] },
  { comment: 'Rate Limiting', keys: ['RATE_LIMIT_MAX', 'RATE_LIMIT_WINDOW_MS'] },
  {
    comment: 'Data retention (days before scheduled cleanup workers delete old data)',
    keys: ['AUDIT_RETENTION_DAYS', 'SESSION_RETENTION_DAYS'],
  },
  {
    comment: 'Email (Resend)',
    keys: ['RESEND_API_KEY', 'EMAIL_FROM_ADDRESS', 'EMAIL_FROM_NAME'],
  },
  {
    comment: 'OAuth (Google)',
    keys: ['OAUTH_GOOGLE_CLIENT_ID', 'OAUTH_GOOGLE_CLIENT_SECRET', 'OAUTH_GOOGLE_REDIRECT_URI'],
  },
  {
    comment: 'OAuth (GitHub)',
    keys: ['OAUTH_GITHUB_CLIENT_ID', 'OAUTH_GITHUB_CLIENT_SECRET', 'OAUTH_GITHUB_REDIRECT_URI'],
  },
  { comment: 'Stripe', keys: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'] },
  {
    comment: 'Sentry — error tracking, tracing, profiling',
    keys: [
      'SENTRY_DSN',
      'SENTRY_ENVIRONMENT',
      'SENTRY_TRACES_SAMPLE_RATE',
      'SENTRY_PROFILE_SAMPLE_RATE',
    ],
  },
  {
    comment: 'S3 / Object Storage',
    keys: ['S3_BUCKET', 'S3_REGION', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY'],
  },
];

function escapeEnvValue(value: string): string {
  if (value === '') return '';
  const hasSpecial = /[\s#"\\]/.test(value);
  if (!hasSpecial) return value;
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function formatEnvFile(environmentName: string, variables: EnvironmentVariables): string {
  const lines: string[] = [
    `# Environment: ${environmentName}`,
    `# Generated by setup:infra — push these to GitHub Environment "${environmentName}" (e.g. gh secret set NAME --env ${environmentName} --body-file .env.${environmentName} or set each key manually).`,
    `# Structure matches .env.example. Do not commit this file (.env.* is gitignored).`,
    '',
  ];

  for (const section of ENV_SECTIONS) {
    const sectionKeys = section.keys.filter(
      (key) => key in variables && variables[key] !== undefined,
    );
    if (sectionKeys.length === 0) continue;
    lines.push(`# ${section.comment}`);
    for (const key of sectionKeys) {
      const value = variables[key as keyof EnvironmentVariables];
      const raw = typeof value === 'string' ? value : String(value ?? '');
      lines.push(`${key}=${escapeEnvValue(raw)}`);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

/**
 * Writes .env.<environmentName> for each environment. Requires config, secrets, and state.
 * Call after provisioning or run standalone via pnpm setup:infra:export-env.
 */
export function exportEnvFiles(): string[] {
  const config = loadConfig();
  const secrets = loadSecrets(config);
  const state = loadState();
  const environments = getEnvironmentNames(config);

  const written: string[] = [];

  for (const environmentName of environments) {
    const variables = buildEnvironmentVariables(environmentName, config, secrets, state);
    const filePath = resolve(PROJECT_ROOT, `.env.${environmentName}`);
    const content = formatEnvFile(environmentName, variables);
    writeFileSync(filePath, content, 'utf-8');
    written.push(`.env.${environmentName}`);
  }

  return written;
}

/**
 * Run from CLI (pnpm setup:infra:export-env). Exits on missing config/state.
 */
export function runExportEnv(): void {
  logger.info('Exporting environment variables to .env.<environment> files...');
  logger.blank();

  const written = exportEnvFiles();

  logger.success(`Wrote ${written.length} file(s): ${written.join(', ')}`);
  logger.info(
    'Push to GitHub: use each file to set secrets for the matching GitHub Environment (e.g. gh secret set NAME --env <env> --body-file .env.<env> or set keys manually).',
  );
}
