/**
 * Project-identity generation policy.
 *
 * The template promise is that ONE edit to `tooling/setup/setup.config.json`
 * renames the whole project. These tests pin the two properties that make that
 * true and are easy to regress: renderers must be rename-safe (never anchored on
 * the current slug) and must not disturb fields another tool owns.
 */
import { describe, expect, it } from 'vitest';
import {
  buildProjectIdentitySnapshot,
  resolveDerivedNames,
} from '@tooling/setup/codegen/project-identity.util.js';
import {
  renderCodeowners,
  renderComposeContainerNames,
  renderPackageJson,
  renderProductionEnvironment,
  renderSonarProperties,
} from '@tooling/setup/codegen/repository-identity-artifacts.js';
import {
  applyTextRewrites,
  mcpTemplateRules,
  TEXT_REWRITE_TARGETS,
} from '@tooling/setup/codegen/text-identity-rewrites.js';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  identityLiterals,
  scanProjectIdentityLiterals,
} from '@tooling/setup/codegen/validate-project-identity-literals.js';
import type { SetupConfig } from '@tooling/setup/common/types.js';

function buildConfig(overrides?: {
  name?: string;
  owners?: string[];
  repository?: string;
}): SetupConfig {
  return {
    project: {
      name: overrides?.name ?? 'acme-api',
      displayName: 'Acme API',
      packageName: overrides?.name ?? 'acme-api',
    },
    git: { protectedBranches: ['main'], defaultBranch: 'main' },
    environments: [
      {
        name: 'production',
        label: 'Production',
        nodeEnvironment: 'production',
        protected: true,
        isDefault: true,
      },
    ],
    providers: {
      github: {
        enabled: true,
        repository: overrides?.repository ?? 'acme-org/acme-api',
        ...(overrides?.owners ? { owners: overrides.owners } : {}),
      },
    },
  } as SetupConfig;
}

const snapshot = buildProjectIdentitySnapshot(buildConfig());

describe('project identity — derived names', () => {
  it('derives every slug-bearing name from the manifest slug', () => {
    const derived = resolveDerivedNames(buildConfig({ name: 'acme-api' }));
    expect(derived.apiServerName).toBe('acme-api');
    expect(derived.webhookUserAgent).toBe('acme-api-webhook');
    expect(derived.sonarProjectKey).toBe('acme-api');
    expect(derived.dbmlPath).toBe('docs/database/acme-api.dbml');
    expect(derived.containers.postgres).toBe('acme-api-postgres');
    expect(derived.containers.sonarScanner).toBe('acme-api-sonar-scanner');
  });

  it('treats the slug and the GitHub owner as the forbidden literals', () => {
    expect(identityLiterals(snapshot)).toEqual(['acme-api', 'acme-org']);
  });
});

describe('project identity — CODEOWNERS', () => {
  it('defaults the roster to the repository owner', () => {
    const codeowners = renderCodeowners(snapshot);
    expect(codeowners).toContain('*                        @acme-org');
    expect(codeowners).toContain('# GENERATED by pnpm tool:generate-project-identity');
  });

  it('emits every configured owner so team governance mode can be satisfied', () => {
    const multiOwner = buildProjectIdentitySnapshot(
      buildConfig({ owners: ['first-owner', 'second-owner'] }),
    );
    const codeowners = renderCodeowners(multiOwner);
    expect(codeowners).toContain('@first-owner @second-owner');
  });
});

describe('project identity — production environment reconcile', () => {
  const baseEnvironment = JSON.stringify(
    {
      name: 'production',
      protection: {
        requiredReviewers: { users: ['previous-owner'], teams: [], preventSelfReview: false },
        deploymentBranchPolicy: { protectedBranches: true, customBranchPolicies: false },
      },
    },
    null,
    2,
  );

  it('replaces a stale owner handle with the manifest roster', () => {
    const result = JSON.parse(renderProductionEnvironment(snapshot, baseEnvironment));
    expect(result.protection.requiredReviewers.users).toEqual(['acme-org']);
  });

  it('never changes fields owned by github:tool:governance-mode', () => {
    const teamEnvironment = JSON.stringify({
      name: 'production',
      protection: {
        requiredReviewers: {
          users: ['stale-one', 'stale-two'],
          teams: [],
          preventSelfReview: true,
        },
        deploymentBranchPolicy: { protectedBranches: true, customBranchPolicies: false },
      },
    });
    const multiOwner = buildProjectIdentitySnapshot(
      buildConfig({ owners: ['first-owner', 'second-owner'] }),
    );
    const result = JSON.parse(renderProductionEnvironment(multiOwner, teamEnvironment));
    // Reviewer COUNT is preserved, so the encoded governance mode is unchanged.
    expect(result.protection.requiredReviewers.users).toHaveLength(2);
    expect(result.protection.requiredReviewers.preventSelfReview).toBe(true);
    expect(result.protection.deploymentBranchPolicy.protectedBranches).toBe(true);
  });
});

describe('project identity — package.json reconcile', () => {
  it('rewrites the name and derives repository coordinates', () => {
    const result = JSON.parse(renderPackageJson(snapshot, JSON.stringify({ name: 'old-name' })));
    expect(result.name).toBe('acme-api');
    expect(result.repository.url).toBe('git+https://github.com/acme-org/acme-api.git');
    expect(result.bugs.url).toBe('https://github.com/acme-org/acme-api/issues');
  });

  it('keeps the committed description when the manifest does not set one', () => {
    const result = JSON.parse(
      renderPackageJson(snapshot, JSON.stringify({ name: 'old', description: 'Keep me' })),
    );
    expect(result.description).toBe('Keep me');
  });
});

describe('project identity — rename safety', () => {
  it('rewrites compose container names from ANY previous slug', () => {
    const compose = [
      'services:',
      '  postgres:',
      '    container_name: totally-different-postgres',
      '  redis:',
      '    container_name: legacy-redis',
      '  sonar-scanner:',
      '    container_name: legacy-sonar-scanner',
    ].join('\n');
    const rewritten = renderComposeContainerNames(snapshot, compose);
    expect(rewritten).toContain('container_name: acme-api-postgres');
    expect(rewritten).toContain('container_name: acme-api-redis');
    // Longest-suffix-first ordering: `-sonar-scanner` must not be shortened.
    expect(rewritten).toContain('container_name: acme-api-sonar-scanner');
  });

  it('is idempotent — re-running produces no further change', () => {
    const once = renderComposeContainerNames(snapshot, '    container_name: old-postgres\n');
    expect(renderComposeContainerNames(snapshot, once)).toBe(once);
  });

  it('rewrites sonar keys regardless of the previous value', () => {
    const properties = renderSonarProperties(
      snapshot,
      'sonar.projectKey=whatever-was-here\nsonar.projectName=whatever-was-here\nsonar.sources=src\n',
    );
    expect(properties).toContain('sonar.projectKey=acme-api');
    expect(properties).toContain('sonar.projectName=acme-api');
    expect(properties).toContain('sonar.sources=src');
  });
});

describe('project identity — text rewrites', () => {
  const snapshot = buildProjectIdentitySnapshot(buildConfig({ name: 'acme-api' }));

  /**
   * Regression: `docker-compose.yml` is touched by TWO rules — container names
   * and the Toxiproxy image tag. When each transform was computed from a fresh
   * read of the file, the second silently discarded the first, so container
   * names kept the base project's slug after an otherwise successful adoption.
   * Transforms must compose.
   */
  it('composes multiple rewrites of the same file instead of clobbering', () => {
    const original = [
      'services:',
      '  postgres:',
      '    container_name: old-postgres',
      '  toxiproxy:',
      '    image: old-toxiproxy:2.12.0',
      '    container_name: old-toxiproxy',
      '',
    ].join('\n');

    const toxiproxyRules = TEXT_REWRITE_TARGETS.find(
      (target) => target.path === 'docker-compose.yml',
    )?.rules;
    expect(toxiproxyRules).toBeDefined();

    // Same order the generator applies them: container names, then text rules,
    // each building on the previous result.
    const afterContainers = renderComposeContainerNames(snapshot, original);
    const composed = applyTextRewrites(afterContainers, toxiproxyRules ?? [], snapshot);

    expect(composed).toContain('container_name: acme-api-postgres');
    expect(composed).toContain('container_name: acme-api-toxiproxy');
    expect(composed).toContain('image: acme-api-toxiproxy:2.12.0');
    expect(composed).not.toContain('old-');
  });

  it('rewrites every target from an arbitrary previous slug and is idempotent', () => {
    const samples: ReadonlyArray<readonly [string, string, string]> = [
      ['.gitleaks.toml', 'title = "whatever gitleaks config"\n', 'acme-api gitleaks config'],
      ['.codacy.yaml', '# Codacy analysis scope for whatever.\n', 'scope for acme-api.'],
      ['.github/release-please/config.json', '{ "package-name": "whatever" }', '"acme-api"'],
      ['tooling/db-viewer/config.json', '{ "name": "whatever" }', '"acme-api"'],
      [
        'src/tests/load/k6/setup-loadtest.sh',
        'docker exec whatever-postgres pg_isready\n',
        'docker exec acme-api-postgres',
      ],
    ];

    for (const [path, original, expected] of samples) {
      const rules = TEXT_REWRITE_TARGETS.find((target) => target.path === path)?.rules ?? [];
      const once = applyTextRewrites(original, rules, snapshot);
      expect(once, `${path} should be rewritten`).toContain(expected);
      expect(applyTextRewrites(once, rules, snapshot), `${path} should be idempotent`).toBe(once);
    }
  });

  it('renames the MCP server key from any previous slug', () => {
    const once = applyTextRewrites('{ "whatever:api": {} }', mcpTemplateRules(), snapshot);
    expect(once).toContain('"acme-api:api"');
    expect(applyTextRewrites(once, mcpTemplateRules(), snapshot)).toBe(once);
  });

  it('never follows a tracked symlink into an untracked file', () => {
    // `.mcp.json` is a tracked symlink to the gitignored, developer-specific
    // `agent-os/mcp/mcp.json`. A stat() that follows links made this gate read a private config
    // (possibly holding API keys) and fail `pnpm ci:quality` on every machine that had scaffolded
    // one — while passing in CI, where the target is absent and the link dangles. That local-only
    // asymmetry is exactly what a repo-wide gate must not have.
    //
    // Built as a throwaway repo rather than asserted against this one: the fixture slug is
    // `acme-api`, which appears nowhere in core-be, so scanning the real tree would pass no matter
    // what the scanner does. A test that cannot fail is worse than no test.
    const scratch = mkdtempSync(join(tmpdir(), 'identity-symlink-'));
    try {
      const git = (...arguments_: string[]): void => {
        execFileSync('git', arguments_, { cwd: scratch, stdio: 'ignore' });
      };
      git('init', '-q');

      writeFileSync(join(scratch, 'private.json'), '{ "server": "acme-api" }\n');
      writeFileSync(join(scratch, '.gitignore'), 'private.json\n');
      symlinkSync('private.json', join(scratch, 'link.json'));
      git('add', '-A');

      const { violations } = scanProjectIdentityLiterals({
        snapshot: buildProjectIdentitySnapshot(buildConfig()),
        projectRoot: scratch,
        generatedPaths: [],
      });

      // Sanity: the literal really is reachable through the link, so a passing assertion below
      // means the scanner skipped it — not that the fixture was inert.
      expect(readFileSync(join(scratch, 'link.json'), 'utf-8')).toContain('acme-api');
      expect(violations.map((violation) => violation.file)).not.toContain('link.json');
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  });

  it('never anchors a rewrite pattern on the current project slug', () => {
    // A pattern containing the live slug is self-disabling: after the first
    // rename it stops matching and the rewrite silently no longer applies.
    const live = identityLiterals(buildProjectIdentitySnapshot(buildConfig()));
    for (const target of TEXT_REWRITE_TARGETS) {
      for (const rule of target.rules) {
        for (const literal of live) {
          expect(
            rule.pattern.source,
            `${target.path} pattern must not contain "${literal}"`,
          ).not.toContain(literal);
        }
      }
    }
  });
});
