import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { createTestApp } from '@/tests/helpers/test-app.js';
import {
  getRouteCount,
  loadRouteRegistryFromCatalog,
} from '@/tests/helpers/route-catalog-registry.js';

const ROUTE_REGISTRY = loadRouteRegistryFromCatalog();
import {
  isAllowlistedRegisteredRoute,
  isApiRoutePath,
  normalizeRegisteredRouteKey,
} from '@/tests/helpers/registered-route.util.js';
import type { FastifyInstance } from 'fastify';

/**
 * Route completeness test — validates generated registry integrity and Fastify parity.
 * Registry is generated by pnpm routes:catalog from domain *.routes.ts sources.
 */

function normalizeRegistryPath(path: string): string {
  if (path.length > 1 && path.endsWith('/')) {
    return path.slice(0, -1);
  }
  return path;
}

describe('Route Completeness', () => {
  let app: FastifyInstance | undefined;
  let registeredRouteKeys: Set<string>;

  beforeAll(async () => {
    const testApp = await createTestApp();
    app = testApp.app;
    registeredRouteKeys = new Set(
      testApp.registeredRoutes.map((route) => normalizeRegisteredRouteKey(route.method, route.url)),
    );
  });

  afterAll(async () => {
    await app?.close();
  });

  it('should have routes defined in the registry', () => {
    expect(getRouteCount()).toBeGreaterThan(0);
  });

  it('every registry entry should have required fields', () => {
    for (const route of ROUTE_REGISTRY) {
      expect(route.method, `Route missing method: ${route.path}`).toBeDefined();
      expect(route.path, `Route missing path`).toBeDefined();
      expect(route.domain, `Route missing domain: ${route.path}`).toBeDefined();
      expect(route.access, `Route missing access: ${route.path}`).toBeDefined();
      expect(route.description, `Route missing description: ${route.path}`).toBeDefined();
      expect(route.path.startsWith('/'), `Route path must start with /: ${route.path}`).toBe(true);
    }
  });

  it('should not have duplicate routes in the registry', () => {
    const seen = new Set<string>();
    for (const route of ROUTE_REGISTRY) {
      const key = `${route.method} ${normalizeRegistryPath(route.path)}`;
      expect(seen.has(key), `Duplicate route in registry: ${key}`).toBe(false);
      seen.add(key);
    }
  });

  it('every domain should have at least one route', () => {
    const domains = [...new Set(ROUTE_REGISTRY.map((route) => route.domain))];
    expect(domains.length).toBeGreaterThan(0);
    for (const domain of domains) {
      const domainRoutes = ROUTE_REGISTRY.filter((route) => route.domain === domain);
      expect(
        domainRoutes.length,
        `Domain "${domain}" should have at least one route`,
      ).toBeGreaterThan(0);
    }
  });

  it('every registry route should be registered on the Fastify app', () => {
    expect(app).toBeDefined();
    expect(registeredRouteKeys.size).toBeGreaterThan(0);

    const missing: string[] = [];
    for (const route of ROUTE_REGISTRY) {
      const path = normalizeRegistryPath(route.path);
      const key = normalizeRegisteredRouteKey(route.method, path);
      if (!registeredRouteKeys.has(key)) {
        missing.push(key);
      }
    }

    expect(
      missing,
      `Registry routes not found in Fastify:\n${missing.slice(0, 20).join('\n')}${
        missing.length > 20 ? `\n... and ${missing.length - 20} more` : ''
      }`,
    ).toEqual([]);
  });

  it('every captured API route should exist in the registry or allowlist', () => {
    expect(app).toBeDefined();

    const registryKeys = new Set(
      ROUTE_REGISTRY.map((route) =>
        normalizeRegisteredRouteKey(route.method, normalizeRegistryPath(route.path)),
      ),
    );

    const unlisted: string[] = [];
    for (const route of registeredRouteKeys) {
      const [method, ...pathParts] = route.split(' ');
      const path = pathParts.join(' ');
      if (!(method && path && isApiRoutePath(path))) continue;
      if (registryKeys.has(route)) continue;
      if (isAllowlistedRegisteredRoute(method, path)) continue;
      unlisted.push(route);
    }

    expect(
      unlisted,
      `Fastify routes missing from generated registry (run pnpm routes:catalog):\n${unlisted
        .slice(0, 20)
        .join('\n')}${unlisted.length > 20 ? `\n... and ${unlisted.length - 20} more` : ''}`,
    ).toEqual([]);
  });

  it('access types should be valid enum values', () => {
    const validAccess = new Set(['public', 'authenticated', 'global-role', 'org-permission']);
    for (const route of ROUTE_REGISTRY) {
      expect(
        validAccess.has(route.access),
        `Invalid access "${route.access}" for ${route.method} ${route.path}`,
      ).toBe(true);
    }
  });

  it('HTTP methods should be valid', () => {
    const validMethods = new Set(['GET', 'POST', 'PUT', 'PATCH', 'DELETE']);
    for (const route of ROUTE_REGISTRY) {
      expect(
        validMethods.has(route.method),
        `Invalid method "${route.method}" for ${route.path}`,
      ).toBe(true);
    }
  });
});
