/**
 * k6 credential-pool helper — per-VU authentication from the pool generated by
 * `pnpm db:seed:loadtest` / `pnpm tool:load-test-credential-pool`.
 *
 * Usage pattern (in a k6 scenario):
 *
 *   import { credentialPool, mintTokenPool, vuToken } from '../helpers/pool.js';
 *
 *   export function setup() {
 *     return mintTokenPool(credentialPool);   // logs in every user once
 *   }
 *
 *   export default function (tokenPool) {
 *     const { token, orgPublicId } = vuToken(tokenPool);
 *     // use token for authenticated requests
 *   }
 *
 * Each VU receives a distinct token — no shared state between VUs.
 * Tokens are minted once in setup() (not per-iteration) so argon2 CPU on the
 * server is exercised N times total, not N*iterations times.
 *
 * The credential-pool.json file is generated by `pnpm db:seed:loadtest` and is
 * gitignored (it contains plaintext passwords). Run the seed before running k6.
 */
import { SharedArray } from 'k6/data';
import { login } from './auth.js';

/**
 * All credential-pool entries loaded from credential-pool.json at init stage.
 * Shared read-only across all VUs — zero per-VU memory overhead.
 */
export const credentialPool = new SharedArray('credential-pool', () => {
  // open() is only valid in the init context (module top-level).
  // If this throws "no such file", generate the pool first:
  //   pnpm db:seed:loadtest
  let raw;
  try {
    raw = open('../data/credential-pool.json');
  } catch {
    throw new Error(
      '[pool.js] credential-pool.json not found.\n' +
        'Run: pnpm db:seed:loadtest\n' +
        'This seeds 120 users into your database and writes the pool file.',
    );
  }
  const pool = JSON.parse(raw);
  if (!Array.isArray(pool) || pool.length === 0) {
    throw new Error(
      '[pool.js] credential-pool.json is empty or invalid.\n' +
        'Re-run: pnpm db:seed:loadtest',
    );
  }
  return pool;
});

/**
 * Mint a JWT for every entry in the pool. Call from setup() once before any VU runs.
 * Returns an array of {token, orgPublicId, userPublicId} — one per pool entry.
 * Entries whose login fails (null token) are filtered out with a warning.
 *
 * @param {Array<{email: string, password: string, orgPublicId: string, userPublicId: string}>} pool
 * @returns {Array<{token: string, orgPublicId: string, userPublicId: string}>}
 */
export function mintTokenPool(pool) {
  const tokens = [];
  for (const cred of pool) {
    const token = login(cred.email, cred.password);
    if (!token) {
      console.warn(`mintTokenPool: login failed for ${cred.email} — entry skipped`);
      continue;
    }
    tokens.push({ token, orgPublicId: cred.orgPublicId, userPublicId: cred.userPublicId });
  }
  if (tokens.length === 0) {
    console.error(
      'mintTokenPool: all logins failed — ensure db:seed:loadtest ran and the server is up',
    );
  }
  return tokens;
}

/**
 * Pick this VU's token entry from the pool minted in setup().
 * Uses round-robin by VU index so every VU gets a distinct identity when pool.length >= maxVUs.
 *
 * @param {Array<{token: string, orgPublicId: string, userPublicId: string}>} tokenPool
 * @returns {{token: string, orgPublicId: string, userPublicId: string}}
 */
export function vuToken(tokenPool) {
  return tokenPool[(__VU - 1) % tokenPool.length];
}
